reddit/reddit-mobile

gulpfile.js
package.json

Mostly wanted to make sure you knew I'm adding superagent back in. The build fails without it so I assume it's still used.

Bump version to v0.3.13. Minor fix to gulpfile and omitted superagent dependency.

---

assets/less/reset.less
src/views/components/Dropdown.jsx

Fixes lists in parsed markdown.

Bring bullets back to ul default styling; use `list-unstyled`

---

README.md

Update to the README file in which the two options for tooling / running
the app and setup "node.js" and "io.js" now have an easily accessible
link to download directly from "Getting Up and Running" instructions
section.

Node.js and IO.js README links

---

README.md

'res.rejcet' was updated to be 'res.reject' as this was a typeo.

Fixing typo in reject promise interface documentation

---

assets/less/components/SideNav.less

Fix: Scroll in the menu on Safari on iOS 8.3

---

README.md

Alternatively, the cloning instructions could say to use `git clone --recursive`

Add submodules to getting started instructions

---

src/views/layouts/DefaultLayout.jsx

Starting with Chrome 39 (for Android 5.0+ and up), it accepts a meta attribute (theme-color) which tells it what to color the address bar with. It also takes the 700 variant of the color and uses it for the status bar to show a darker version of the address bar.
This can be whatever color Reddit prefers it to be (for branding and such), but I think the presence of any color makes the page feel "more at home" for users who are using Android Lollipop.

Add theme-color attribute for Android 5.0+

---

assets/less/components/listing.less

Preventing links/text from protruding outside of the page on low width devices (witnessed on iPhone), as seen on https://m.reddit.com/r/IAmA/comments/35q9z7/i_am_bill_nye_ceo_of_the_planetary_society_joined/.

Style change fix

---

src/server.jsx

If the user came from the desktop site after visiting the desktop for the first time within the last 5 minutes, treat them as a new user for experiments.
:eyeglasses: @umbrae

Date-based referrer logic for "new user" setting

---

src/oauth.es6.js
src/server.jsx

:eyeglasses: @danehansen or @curioussavage 
The wrong oauth client id was being used for converted sessions, so refreshing the token was failing and redirecting users to the home page.

Fix redirect on expired tokens

---

src/views/components/ListingContent.jsx

Fixes the cases when:
* An image is expanded, and the image that should replace the nsfw variant is a preview image;
* An NSFW placeholder should display on a comments page
Fixes #217

Handle nsfw-hiding properly

---

src/server.jsx

Compact should be either `true` or `undefined` to make CF logic easier.

Nuke compacttest; unset `false` compact cookie

---

buildTasks/js.js
package.json

Example:
```js
// This:
if (process.env.NODE_ENV === 'development') {
console.log('dev!');
}
// Turns into this:
if ('production' === 'development') {
console.log('dev!');
}
```
Uglify is able to strip the latter via dead code removal, but not
the former.
See https://github.com/reddit/reddit-mobile/issues/247#issuecomment-118551305 and https://facebook.github.io/react/downloads.html#npm for more info.

Replace env variables with strings

---

assets/js/client.es6.js
src/routes.jsx
src/views/components/TrackingPixel.jsx
src/views/pages/index.jsx
src/views/pages/listing.jsx
src/views/pages/search.jsx
src/views/pages/subredditAbout.jsx
src/views/pages/userActivity.jsx
src/views/pages/userGild.jsx
src/views/pages/userProfile.jsx
src/views/pages/userSaved.jsx

Should eventually maybe wrap up TrackingPixel in a way that isn't so copypasty.

Move referrer to property; clear after first page load

---

src/views/components/Ad.jsx

Impressions are only being checked on scroll/resize.  This also checks immediately after the ad is loaded.
The problem before is that I could refresh the page over and over and never have the impression counted so long as I didn't scroll.
:eyeglasses: @curioussavage @zeantsoi

Impression tracking

---

assets/js/client.es6.js
src/routes.jsx

`loid` was being grabbed from the bootstraped data which in some
cases is cached by the cdn.  This properly takes it from the user's
cookies.
https://m.staging.wireddit.com/
lgtm

Fix loid caching issue

---

src/app-mixin.es6.js
src/redirects.jsx

Also notifying @kjoconnor and @umbrae 
The new version of koa-router doesn't support regexes anymore, which means we need to use `param` filters, as seen below. I also moved redirects above `routes` for higher priority and added `return`s so that multiple route-matching functions don't end up being called.

Rewrite redirects using `param` instead of regexes for koa-router

---

src/redirects.jsx

Match /r/:subreddit/hot, etc directly instead of /r/:subreddit:sort,
which was catching /r/:subreddit/search and such.

Update the routes to match subreddit urls less aggressively

---

assets/js/client.es6.js

Previously, the 'popstate' event listener checked to see if your url had
changed. This is no longer necessary now that events are not bound until
_after_ the app render, and may fix some issues with prev/next browser
cache reloading.

Remove popstate safety check

---

assets/js/client.es6.js
src/app-mixin.jsx

* Don't route the app if we're in the middle of refreshing the token,
cutting down on unnecessary auth errors
* Show a loading screen while oauth is being refreshed, if you try to
change the route in the middle, so things don't freeze
* Fixes a current bug where if you're away for a while, then come back,
you're taken to a login screen
:eyeglasses: @curioussavage or @umbrae 
To test:  set `expires = Date.now()` right after `var expires = new Date(app.getState('tokenExpires'));` in `client.es6.js`, watch for the token to change on the next api request. woo :tada:

Client oauth refresh improvements

---

src/app-mixin.jsx

Fixes, among other things, API_PASS_THROUGH_HEADERS config. Probably means we should find a better method for calling out to the API as part of `app` or something eventually.
:eyeglasses: @curioussavage or @umbrae.

Use apiOptions from props for user info

---

assets/less/components/comment.less
assets/less/components/text.less
src/views/components/Comment.jsx
src/views/pages/listing.jsx

On the ferry this morning, I made some small tweaks:
* Change `[score hidden]` to `[?]` to save space
* Change `Load more comments (57 replies)` to `Load 47 replies`
* Reduce horizontal padding for nested comments by a couple pixels per nesting level
* Increase vertical padding slightly for individual comments
* Reduce vertical padding after comment box
* Increased hit area on text (which shows upvote/downvote/reply/etc)
* Fixed bug where the color won't change on vote icons until you click something else, after voting
New (left) vs Old (right)
:eyeglasses: @curioussavage, @tdohz

Comment minor improvements

---

assets/less/components/text.less
src/views/components/Comment.jsx

To be used when an icon is used inline with text, rather than as a nav / heading / etc.

Add new `icon-inline` class to fix icon color in links

---

assets/js/client.es6.js
src/app-mixin.jsx
src/lib/errorLog.es6.js
src/routes.jsx
src/views/pages/BasePage.jsx

* add requestUrl to the error log, so we can see _where_ errors are happening on the server
* also emit a body replacement event on the client; because everything's async, errors were just showing loading spinners forever
* add props to the context on client-side error handling, so we can render error pages properly

Add request url to errorlog, and fix client-side error pages

---

src/views/components/ListingContent.jsx

the first image resolution is for a thumbnail with
a different aspect ratio
turns out this was all that is necessary. tested with compact/ listing view. thumbnail is unaffected

ListingContent: use second resolution provided for ads case

---

src/server/oauth.es6.js

The post to password flow works (`/api/fp/1/auth/access_token`) but the post to session conversion / modhash list (`api/v1/authorize`) isn't happy.
:eyeglasses: @umbrae

Session conversion does not like * scope

---

index.js
package.json
src/server/config.es6.js
src/server/index.jsx

:eyeglasses: @umbrae, @spladug
This adds:
* Total requests
* Request timings
* Total active requests
* Response code
Buffered to a 100ms timeout by default, configurable.
Questions:
* Should I sample?

Add statsd monitoring of servers

---

src/server/index.jsx

If middleware (such as route handlers) broke on an uncaught exception, it didn't decrement the active requests value, giving us a potentially incorrect `active` count.

Still decrement requests even if middleware fails

---

assets/less/components/Listing.less

Fixes word break so that it breaks in the middle of long words or at spaces, but not in the middle of short words.

Fix word break on listing titles

---

assets/js/client.es6.js
assets/js/trackingEvents.es6.js
src/lib/errorLog.es6.js
src/routes.jsx
src/server/oauth.es6.js
src/server/routes.es6.js
src/views/components/Ad.jsx

:eyeglasses: @umbrae, @curioussavage 
This covers all of our superagent requests. Bad hivemind and oauth requests will hang for 4 minutes each, without timeouts set.
Next step: fork superagent and allow setting a default timeout. Also, implement response timeouts in the http server that will send back a timeout if the server's taking to long (although we still need to kill the open http requests using superagent timeouts.)

Add timeouts for superagent requests

---

src/views/components/ListingList.jsx
src/views/components/TextSubNav.jsx

You cannot set a `ref` on a stateless component - this was throwing
warnings. This commit also fixes the ref to `ul` on TextSubNav, which
was throwing errors on the same page.

Don't set ref on CommentPreviews

---

src/server/index.jsx

Only get the env vars at startup time; it's unnecessary to get them
every request.

Set defaultConfig as constant in server

---

assets/js/client.es6.js
assets/js/trackingEvents.es6.js
src/app-mixin.jsx
src/constants.es6.js
src/routes.jsx
src/server/oauth.es6.js
src/server/routes.es6.js
src/views/components/Ad.jsx

Put default API timeout (which cancels the request and returns a 504 if exceeded) into constants so that it's defined in one place. (One exception: hivemind requests, which we're okay with failing if they take
over a few seconds.)
Also increase API timeout to 10s to accomodate slow requests, like the google crawler. It was set to 5s previously when we thought that api requests were causing the request queue to back up, which does not appear to be the case.

Configurable (and increased) API timeouts

---

src/views/pages/userProfile.jsx

This is currently loading the logged-in user's data instead of the
profile you are attempting to view. This uses the correct property.

Fix userProfile loading from `user` instead of `userProfile

---

assets/js/trackingEvents.es6.js

:eyeglasses: @curioussavage or @schwers, and @drunken-economist 
Send the boolean instead of 'T' / 'F'.

Send boolean instead of T/F in event tracking

---

src/server/index.jsx

:eyeglasses: @schwers @umbrae
Don't nuke cookies just because expires exists - nuke them because expires exists while one of the required cookies doesn't.

Only nuke broken cookies

---

assets/less/components/Listing.less
src/views/components/Listing.jsx

:eyeglasses: @ajacksified @curioussavage @umbrae 
Code review pass for now. Seems like Chrome on iOS has performance problems when the transform is applied to `.Listing` cards.  I added `will-change` transform as fallback.
edit: I originally removed z-index as it seemed unnecessary and seems to fix the bug transform was supposed to fix (compact menus). But that breaks modals on debug on desktop chrome. So I've left z-index in for debugging / future-proofing.
[my local install](http://192.168.129.24:4444/) has these changes
https://reddit.atlassian.net/browse/MOBILEWEB-367

Fix performance issue in iOS chrome from transform

---

src/routes.jsx
src/views/components/InfoBar.jsx
src/views/layouts/BodyLayout.jsx

`routes.jsx` was setting a key on the `BodyLayout` it created to wrap
pages. This was to make `InfoBar` be reused for tracking reasons. This
broke properties set on `BodyLayout` from updating correctly across pages
(when those properties are promises who’s result depends on the state
of rest-cache). This change makes `InfoBar`’s tracking independent of
it’s parent and allows promise based props on `BodyLayout` update
correctly.
:eyeglasses: @curioussavage @ajacksified

Make properties on BodyLayout pages update correctly.

---

assets/js/client.es6.js
src/routes.jsx

Noticed these errors popping up, looks like one of the causes is about pages not setting topNavLink.
Also prevents the error from happening in `client.es6.js`. Alternatively we could catch it and log it to see where else it happens. Thoughts? :eyeglasses: @curioussavage or @ajacksified

Fix indexOf undefined errors when clicking links without an href.

---

src/views/components/ListingContainer.jsx

I've been seeing errors for 'name' of undefined in `ListingPaginationButtons.jsx`. This fix bails out of rendering pagination buttons when there are no listings as the buttons component relies on having them. Doesn't make sense to show them when there are no listings either.
:eyeglasses: @ajacksified @curioussavage

Don't render pagination buttons when there are no listings

---

src/server/index.jsx

Been noticing this error in the log. It looks like some of the requests don’t have a userAgent so that could be the real underlying issue. But in a lot of cases it looks like we check for user-agent not being null so this seems like a valid fix.

Fix match of undefined error (log cleanup)

---

src/views/components/ListingContent.jsx

:eyeglasses: @ajacksified or @curioussavage or @nramadas 
I've noticed this error popping up in the logs. An alternative would be to provide empty string default via Snoode but this might be the only case where this is an issue

Fix null listing url check (log cleanup)

---

assets/less/components/Listing.less

It looks like scrolling is awry again. No recent changes in the code
would have caused this. In-fact the issue is present when
time-traveling back to 94cda4847f15ea1e4b8a12b42a3b7b42dce6a319
Google Chrome has no updates listed in the App Store, so I think it’s
an issue with either iOS version 9.2 or 9.3 (testing with 9.3)
:eyeglasses: @ajacksified and @curioussavage (not sure what version you're on Adam, but let me know. Let's do a round of more testing in the morning)

Unjankify iOS Chrome scrolling again.

---

.eslintrc
assets/js/client.es6.js
src/app-mixin.jsx
src/routes.jsx
src/server/index.jsx
src/views/components/ListingContainer.jsx
src/views/components/ListingPaginationButtons.jsx
src/views/components/NotificationBar.jsx
src/views/pages/index.jsx
src/views/pages/search.jsx
test/views/pages/Index.jsx

Instead, use the old ones, and implement a more user-friendly "no links" error message, helping the user load fresh links.
Obviously needs design help, but is this what you were thinking about, @umbrae?
:eyeglasses: @umbrae and @curioussavage or @schwers

Don't try to load fresh links when you restore a tab, and alert user about stale next/previous

---

src/routes.jsx
src/views/layouts/BodyLayout.jsx

BodyLayout now takes an optional prop that will hide
the topnav. All pages can now be rendered through body
layout so we can use it for app wide errors and notifications.
@schwers or @nramadas 
For the new login/registration page, which does not have the `topNav` anymore. Instead of rendering it with a custom body function We now pass a flag to indicate the `topNav` should be hidden. 
Also makes it so `bodylayout` can own the toasts since it will always be rendered.

Bodylayout: include on everypage

---

assets/js/client.es6.js
src/app-mixin.jsx
src/lib/errorLog.es6.js
src/server/index.jsx
src/server/routes.es6.js

This adds the ability for the client to send error logs to the server, which will be `console.log`. You can then grep the server logs for output to see what's going on on the client. Includes stack traces if available.

Super simple client error logging

---

assets/js/client.es6.js
src/config.es6.js
src/routes.jsx
src/views/components/CommentBox.jsx
src/views/components/CommunityHeader.jsx
src/views/components/TopSubnav.jsx
src/views/components/UserActivitySubnav.jsx
src/views/components/UserOverlayMenu.jsx
src/views/components/Vote.jsx
test/index.js
test/routes/loginRegisterOriginalUrl.es6.js

This changes login/register to be regular links. They no longer require
setting `data-no-route={ true }` or setting the originalUrl. Cleans up
`app.redirect` in `client.es6.js` and removes duplicated logic in the
click handlers to make this possible.
Adds a `REGISTER_PATH` that automatically is `/register` for apps that
use `/login`.
The app links to `LOGIN_PATH` when there’s a good  chance the user is
intending to log in to an existing account. eg if they click ‘log in’
on the top of the page or user menu. Otherwise when an action that
requires having an account is performed `app.needsToLogInUser` will
properly redirect to `REGISTER_PATH`
For testing: Should be tested in staging to make sure the non-development `originalUrl` validation is working as intended

Make login/register use real links and redirect back properly.

---

src/views/components/OverlayMenuRow.jsx

Some of the new subreddit icons rely on the transparency of icon images to render properly. Eg r/apple
In this patch:
Versus prod:
:eyeglasses: @ajacksified or @curioussavage or @nramadas

Set background to key_color on community header icons

---

src/views/pages/search.jsx

Fixes `search.jsx` to show the no results message when expected.
Removed the var `noResult` as it was impossible for it have any value where it was being used. Cleans up the checks a little.

Show the no results warning correctly

---

src/server/oauth.es6.js

When logging in times out there was no response object. This
Fixes a TypeError that was being thrown because of attempts to
look up properties on it.

Login/Register: Fix bug with timeout

---

assets/js/client.es6.js
src/routes.jsx
test/routes/loginRegisterOriginalUrl.es6.js

Safari triggers a popstate event on initial render.
On the login route this was causing it to render the
page again with the wrong referer.

Bug Fix: prevent render on first popstate in safari

---

src/views/pages/BasePage.jsx

Avoid extra synchronous setstates on the server by only setting state on
the client once all of the data loads.

Only run `finish` setstate on the client

---

src/views/pages/listing.jsx

Addresses: https://reddit.atlassian.net/browse/MOBILEWEB-393
The issue was pretty simple. When we received new data, we chose not to use it (derp). This patch fixes that by actually replacing `data` with `newData`.

Fix 'load more comments" link

---

src/views/pages/BasePage.jsx

I noticed a strange anomaly: error logs were multiplying on pages with
single errors. For example, a failed API request would turn into four -
and pages with five API requests would turn into twenty. I tracked it
down to basepage, and with some debugging, noticed that error logging
was called by: layout, indexpage, layout (again), and errorpage.
This is due to layout, indexpage, and error page inheriting from
basepage, which sets up watchers on the promises. This is used to run
setState on pages, but *also* logs on errors - and as they share the
same promises, it also means that both layout and page will error, and
then again when redirected with a clone of the properties from the
previous page.
This sets a flag on the shared promise so that it won't re-log after the
first failure.
That's …

Set a flag on promises so all `then`s do not log

---

src/lib/isFakeSubreddit.es6.js
src/routes.jsx
src/views/pages/index.jsx
test/index.js
test/lib/isFakeSubreddit.es6.js

Right now manual multis (like `/r/destinythegame+halo+division` fetch
links but are never rendered by the ListingPage because there were two
different definitions of fake subs in the code. Along the way adds
support for random and randnsfw

Support manual multis, random, and randnsfw

---

src/lib/errorLog.es6.js

change the separator so we can parse logs easier.
The tabs get stripped out of our log files.

Logs: changes separator to |

---

package.json
src/lib/errorLog.es6.js
src/server/console.es6.js

This uses the typed errors from https://github.com/reddit/snoode/pull/78 to report API errors separately from code errors. https://github.com/reddit/hivemind/pull/23 adds the error segment.

Separate api errors

---

assets/js/client.es6.js

Depends on:
* [Snoode Pr 75](https://github.com/reddit/snoode/pull/75) that fixes api.hydrate so we wait less for the pageview event
Which depends on  [RestCache Pr 4](https://github.com/reddit/restcache/pull/4) That makes Cache.generateHash work in a deterministic way
This patches first commit fixes the improper way we call postRender right now. I introduced this in [login/register](https://github.com/reddit/reddit-mobile/commit/28fef9da2b97e428d58a10ae2eadde9e92b76505) :(
The second commit makes postRender update scroll position in a second pass after data loads in, _iff_ the page hasn't been manually scrolled. This way if things take a while to come out of the cache (i.e. they're evicted or because Promise.resolve is in a new callstack), the scroll position is updated as expected

Preserve scroll position in smarter ways

---

package.json
src/app-mixin.jsx

This was previously causing too much noise, but now that API errors are separated out, it would be a good thing to track. We should keep an eye on whether this slows down response times while it waits on logging to stdout if things get busy.
We may also want to track incoming API responses the same way we track outgoing HTTP codes, eventually.

Begin tracking API 504s and 429s

---

src/views/components/listings/PostAndCommentList.jsx
src/views/components/listings/PostDropdown.jsx
src/views/components/listings/PostHeader.jsx

Ads don't have a subreddit and this was cause links to
`/r/undefined`.
before:
after:
also moved the ads back down.

Undefined subreddit

---

assets/less/components/communities/CommunityRow.less
src/views/components/CommunityOverlayMenu.jsx
src/views/components/OverlayMenuRow.jsx
src/views/components/communities/CommunityRow.jsx

This adds r/ to subredit display names in the community menu and in search results. We're doing this when rendering posts and post dropdrowns, so this makes things consistent. Especially because the r/ makes things feel uniquely Reddit. Both of these cases are lists so the distinction is smaller and lighter than normal font to make scanning the list easier.

Add r/ distinction to subreddit names

---

src/views/components/Ad.jsx
src/views/components/listings/PostAndCommentList.jsx

`props.token` was undefined.  It seems like a lot of components specify `token` as a `propType` and in some of them it's not used, but there might be issues elsewhere.  Would it be cleaner to reference it from the `ctx` always instead of passing it through to all these components?
```
Searching 690 files for "token: T.string," (case sensitive)
/Users/dwick/work/code/reddit-mobile/src/views/components/LinkTools.jsx:
16      onNewComment: T.func,
17      onSortChange: T.func,
18:     token: T.string,
19      isLocked: T.bool,
20      sort: T.string,
/Users/dwick/work/code/reddit-mobile/src/views/components/comment/Comment.jsx:
41      user: T.object,
42      sort: T.string,
43:     token: T.string,
44      op: T.string,
45      nestingLevel: T.number, …
```

Ads: Request ad as an authenticated user if logged in

---

assets/less/base.less
assets/less/components/comment/Comment.less
assets/less/components/listings/PostContent.less
assets/less/components/tables.less

This adds borders and padding so that tables are easier to read in comments and links.
:eyeglasses: @nramadas

Improve table display in links/comments

---

package.json
src/server/index.jsx
src/server/routes.es6.js
src/views/components/GoogleCarouselMetadata.jsx
src/views/components/LiveReload.jsx
src/views/layouts/DefaultLayout.jsx
src/views/pages/listing.jsx

This restricts the domains that can host content that is run on mobile
web. The headers added are:
* Self to scripts, styles, and fonts, which lets us load locally
* Localhost for scripts, for livereload
* Google analytics for scripts, for obvious reasons
* ASSET_URL from config, for cdn'd stuff
:eyeglasses: @nramadas (for smart banner) and @spladug

Add CSP headers

---

src/redirects.jsx

:eyeglasses: @ajacksified or @schwers 
this is mostly for the /live because of this https://reddit.atlassian.net/browse/MOBILEWEB-405 issue.
I'm not sure what will fix that, but either way I think its not a bad thing to have this redirect there. And it sucks that there is an active thread now and its pointing to an error page for mobile
The rules endpoint just mirrors what r2 does - send this url to the content policy

redirects: add /live and /rules

---

src/views/components/UserOverlayMenu.jsx

looks like this one slipped through code review. missing click handler

userOverlayMenu: add correct click handler to desktop link

---

assets/js/clientEvents.es6.js
index.js

this can help us find promises that need
rejection to be handled. currently only works
in chrome on the browser
👓  @ajacksified @schwers @nramadas 
I think this is really handy, just like `uncaughtException` its a nice helper in dev. only available in chrome right now though :(
see:
http://www.2ality.com/2016/04/unhandled-rejections.html?utm_source=javascriptweekly&utm_medium=email

Add unhandledrejection listener on server and client

---

src/views/components/Ad.jsx
src/views/components/listings/PostAndCommentList.jsx

Requires sending the list of thing fullnames that are rendered on
the page to request_promo as the param `dt`.
Change on .com: https://github.com/reddit/reddit-public/commit/1d4b9513d02bfd93168a06243ccede04e9bea732#diff-80017b87156838d1be01f5830f588095R173
👓 @curioussavage @tsegaran

Ads: Add support for keyword targeting

---

src/views/components/listings/Listing.jsx
src/views/components/listings/PostAndCommentList.jsx

Not having this property was causing the site to always be
`_FRONTPAGE_NAME` in `getSite`.
👓 @schwers

Ensure `subredditName` is supplied to `PostAndCommentList.jsx`

---

src/lib/smartBannerState.es6.js

Expand the list to every country but the following: Brazil, Germany, France, Indonesia, Iran, Cuba, Myanmar, and Sudan.
:eyeglasses: @nramadas, it looks like you were the last person to touch this code.

Expand the country list for the native app banner

---

assets/js/client.es6.js
src/lib/smartBannerState.es6.js

Native mobile is launched in all countries now,
so remove the country filter as it's no longer needed.
:eyeglasses: @phil303 @schwers

Remove country filter from the smart banner

---

src/Server.js
src/server/meta/index.js

We need to support `/robots.txt`, `/routes`, and the apple app site
assocation routes.

Add some metadata routes from 1X

---

assets/less/components/comment/CommentHeader.less

This fixes the comment caron icon being a few pixels off vertically
Before
After
👓 @phil303 or @nramadas

Fix comment caron icon vertical alignment

---

package.json
src/Client.js
src/app/actions/posts.js
src/app/components/Post/PostContent/index.jsx
src/app/components/Post/index.jsx
src/app/less/components/aspect-ratio.less
src/app/reducers/expandedPosts.js
src/app/reducers/expandedPosts.test.js
src/app/reducers/index.js
src/app/side-effect-components/LocalStorageSync.js

This adds post expanding behavior from mweb 1x. 
There was a change to `aspect-ratio.less` [commit](https://github.com/reddit/art-gallery/commit/d4dbd5bea64e8dc7bde2c76301d3259ba78126c6) that was trying to remove padding to fix hit areas on comments pages. That fix should have been removing the height set the images rendered by `PostContent` because the difference in that height versus the `aspect-ratio` seems to be what was really causing issues. This needed to be reverted in this patch to fix expands, and actually card view in general.
This depends on https://github.com/reddit/node-api-client/pull/127 to ensure the failed https requests to  `http:self` disappear and fixes empty preview images

Enable post expanding

---

src/app/actions/wiki.js
src/app/components/SubredditAbout/index.js
src/app/components/Wiki/index.js
src/app/components/Wiki/styles.less
src/app/models/WikiRequest.js
src/app/pages/AppMain.jsx
src/app/pages/WikiPage.jsx
src/app/reducers/index.js
src/app/reducers/wikiRequests.js
src/app/reducers/wikiRequests.test.js
src/app/reducers/wikis.js
src/app/reducers/wikis.test.js
src/app/router/handlers/WikiPage.js
src/app/router/index.js
src/lib/makeWikiPath.js

Handles cases of /w, /w/ and /w/:path, and
/wiki and /help variants of it, as well as
/r/:subredditName/w/* and /r/:subredditName/wiki/*
This implementation only reads and we'll probably
want to add stuff like revision and page views,
but it's a start.
👓  @schwers @phil303

Add Wiki support to Mobile Web 2X

---

src/Server.js
src/server/meta/index.js

Ports from 1X of the `/timings`, `/csp-report`, and `/error` behavior.
Small change to the apple app-site association data, so that we don't
match on all paths (`/`) but do continue matching on `/comments/*` paths.

Add routes for feedback data from the client

---

src/views/components/Inbox.jsx
src/views/components/MessagePreview.jsx
src/views/pages/messages.jsx

The mobile web messages view has an "All" view, which should not show a
user's own replies, and a "Messages" view, which should show a user's
reply (nested under the original message). The user can compose a reply
from both views, but we should only add the submitted message to the
view if we're in the "Messages" view.

Avoid showing replies in inbox mode

---

assets/js/client.es6.js
assets/js/clientLib.es6.js
src/constants.es6.js
src/featureflags.es6.js
src/routes.jsx
src/views/components/GoogleTagManager.jsx
src/views/layouts/BodyLayout.jsx
src/views/layouts/DefaultLayout.jsx
src/views/pages/index.jsx

👓 @prashtx 
ticket: https://reddit.atlassian.net/browse/ADS-567
(comscore/gtm are also disabled for no_ads group: https://reddit.atlassian.net/browse/ADS-579)
had to move the gtm code from the default layout to the bodylayout since it requires the user's `me.json` data.
using this existing feature config: https://github.com/reddit/reddit-private/blob/e918abff41544cfc0f67f29025869b52b1b87089/production.ini#L1229
forced variant:
normal:

Add `no_ads` experiment

---

assets/js/trackingEvents.es6.js
assets/less/base.less
assets/less/components/NextContent.less
assets/less/components/RelevantContent.less
assets/less/components/icon-font.less
package.json
src/constants.es6.js
src/featureflags.es6.js
src/lib/visitedPosts.es6.js
src/routes.jsx
src/views/components/listings/RelevantContent.jsx
src/views/pages/listing.jsx

Support 4 next-content variants (middle carousel, bottom, banner, top
3). The "middle" variant shows a swipeable set of the top unread posts
from the current subreddit, positioned between the current post and the
comments. The "bottom" variant shows the top unread post from the
current subreddit, fixed to the bottom of the viewport. The "banner"
variant behaves like "bottom" but appears only after the user scrolls
and sits just above the bottom of the viewport. The "top3" variant is
identical to the "top3" variant of the relevancy_mweb experiment. The
experiment is not restricted to a particular subreddit.
Track the 10 most recently viewed posts, so that we can show new content
to logged-out and logged-in users.

Add next-content experiments

---

src/featureflags.es6.js

If we build more experiments into mweb 1X, we should move to the new `@r/flags` version, which handles boolean rules better than the interim versions in `featureflags.es6.js`.

Fix typos in the nextcontent_mweb feature configs

---

assets/js/clientEvents.es6.js
src/lib/dom.es6.js
src/server/index.jsx

Right now, mweb users who go to a www url will have their mweb redirect cookie respected. Mweb users who go to an m dot url will not. This patch adds the ability to respect that cookie on the mweb server.

Redirect m. users to desktop if cookie exists

---

assets/js/trackingEvents.es6.js

Fixes `/login` and `/register` pages from rendering as blank when you go there via an in-app navigation. 
The adblock tracking code is throwing an exception because the adblock test isn't rendered on that page, which breaks rendering. I modified the tracking to not test for adblock when we know the `div#adblock-test` won't be on the page, which would guarantee a false-positive. I changed `testAdblock` to not throw exceptions when the div isn't found.
👓  @dwick

Fix adblock tracking from throwing exceptions

---

assets/js/trackingEvents.es6.js
src/views/layouts/BodyLayout.jsx

We want to test for adblock on every page.  Google tag manager
should continue to be excluded for users with ads disable though.
👓 @schwers 
related to https://github.com/reddit/reddit-mobile/pull/654/files

Always render adblock test element.

---

src/app/components/SVG/index.jsx

I'm not sure what mweb browers don't support SVG. This check was causing an error in the console which was a bit maddening. Removing it cleans up that warning and a bunch of code.
Sweet relief.
:eyeglasses: @schwers @nramadas

remove svg compatibility check

---

package.json
src/app/components/CommentsPage/CommentsPageTools/index.jsx
src/app/components/CommentsPage/CommentsPageTools/styles.less
src/app/components/Dropdown/styles.less
src/app/components/PostAndCommentList/index.jsx
src/app/components/SortAndTimeSelector/index.jsx
src/app/components/SortSelector/index.jsx
src/app/components/SortSelector/styles.less
src/app/components/SubNav/index.js
src/app/pages/Comments.jsx
src/app/pages/PostsFromSubreddit.jsx
src/app/pages/SearchPage/index.jsx
src/app/pages/UserActivity/index.jsx
src/app/pages/UserProfile/styles.less
src/app/router/handlers/CommentsPage.js
src/app/router/handlers/PostsFromSubreddit.js
src/app/router/handlers/SearchPage.js
src/app/router/handlers/UserActivity.js
src/app/sortValues.js
src/lib/listingTime.js

(edit: widgets patch merged, no longer dependent)
This patch adds sorting and time filtering selectors for lists of posts and comments. Comments don't completely work, but are included to get an MVP of this feature into 2X. Comments will need some api work, because the comment tree is stored ad-hoc in each individual comments' `.replies` field. e.g. Go to a comments page sorted by best (a), change sort to top (b), and then back to best (c). You may notice on page (c) that some comment replies aren't ordered the same as page (a) even though they have the same exact sort.

Sort and Time selectors. Doesn't include comment tree updates.

---

assets/js/client.es6.js

From the logs, we seem to get a surprising number of 401s and 404s. In both cases we're autoretrying on the client which defeats the purpose of https://github.com/reddit/reddit-mobile/pull/666, and in the 404 case we often will get the same 404 response back on the client anyway. 
👓  @nramadas

Prevent client retrying 4XX statuses too

---

src/views/pages/index.jsx

Turns out that data.preferences is the place to look.
It also doesn't appear that props.prefs is used, so removing that.

Fix hiding ads based on user preferences

---

assets/less/components/comment/Comment.less
assets/less/components/comment/CommentContinueThisThread.less
assets/less/components/comment/importAll.less
src/views/components/comment/Comment.jsx
src/views/components/comment/CommentContinueThisThread.jsx

When a comment thread goes deeper than the maximum
levels to render a tree, it was displaying
"More comments (0)" and the action was failing.
This makes it so the behavior is more in line with
the desktop site in which it will load the comment
tree from the given point after clicking a
"Continue this thread" message.
This is how desktop handles it:
This is how it's currently handled:
This is if you click on it right now:
This is after the change:

Handle comment threads that are too deep

---

src/app/components/Comment/index.jsx
src/app/pages/Comments.jsx

The comment model has the permalink as a
cleanPermalink attribute, so use that rather
than constructing it.

Remove permalinkBase as it's not used.

---

src/app/components/ErrorPage/index.jsx
src/app/components/ErrorPage/styles.less

`Error` is far too generic a term so make this selector more specific by calling it `ErrorPage`.

Change badly named css selector

---

src/app/components/UserProfileSummary/index.jsx

👓 @phil303 @nramadas 
This is how it is:
This is how the patch makes it:
An alternative would be a variant of what we do if you view someone else's profile:
Instead of "give foo gold", it could be a "Buy gold"... which, granted isn't implemented yet.

Hide GoldInfo if user has no gold

---

src/config.es6.js
src/routes.jsx
src/views/layouts/DefaultLayout.jsx

For self post pages rendered on the server, we need to add a link
element pointing to the equivalent AMP page, which is how we make the
AMP page visible to the world. Without a configured value, we will not
include an element, so this can be turned on/off via the AMP environment
variable.

Add the amphtml link element for self posts

---

src/routes.jsx
src/views/pages/listing.jsx

There are some routes that would be helpful to fix in 1X, and this takes care of that.
Adds `/comments/:listingId/:listingTitle/:commentId` and fixes a bug with `/comments/:listingId/:listingTitle?`
👓 @phil303 @nramadas

Fix a couple of routes

---

src/app/components/LoginRegistrationForm/styles.less
src/app/components/Register/index.jsx

Made cosmetic fixes to the Register page.
- Change error tag from <span> to <p>, a block level html tag
- Add `DEFAULT_ERRORS` for handling `errorType` = 'UNKNOWN_ERROR'
- Change default error text to red
👓 : @nramadas

Cosmetic fixes for Register page

---

src/routes.jsx

We assume that promise values in `props.data` will resolve to objects,
so we should avoid resolving them with `undefined`, even if we we're in
a situation where the value has become irrelevant.

Resolve data promises with non-undefined

---

src/constants.es6.js
src/lib/visitedSubreddits.es6.js
src/routes.jsx

There was an error occurring on the server side. 
My understanding is that `indexPage` in routes.jsx is executed both on the client and server side. This comes from the following screenshot in which I put debugging code in the method and found the statement printed both in my browser and terminal
This was what was occurring in production: I was getting a bunch of server errors but was confused as to why the cookie set anyways. The above explanation is my best hypotheses as why that is occurring, although I have not been able to locate the reason why routes.jsx runs both on client side and server side
**Solution**
I check to make sure cookies are enabled. This lets the client running the code to set the cookie, while when the server runs it, because there are no cookie or localstorage …

Interest targeting fix 1 x

---

.eslintrc
package.json
src/Server.js
src/config.js
src/server/meta/stats.js

We log stats to graphite via statsd -- so add that
packages along with its base configuration.
Initial stats are counting the number of requests
as well as the response error codes.

Add statsd, and request and response error code stats

---

src/lib/isFakeSubreddit.es6.js

We get a lot of hits to `r/all-<subreddit-A>-<subreddit-B>-...-<subreddit-Z>`. This filtered view of `r/all` is valid for gold users, otherwise we return the normal list of posts. However our fake subreddit detector doesn't consider this filtered view to be faking, causing an error when we try to fetch subreddit info.
👓  @prashtx @nramadas

Count filtered r/all as a fake subreddit

---

assets/js/clientEvents.es6.js

This ends up bubbling to the error handler which
wants to check ctx.env, but ctx is undefined.  Instead
we pull ctx from app.state.
👓  @schwers @nramadas

Fix unhandledrejection listener passing undefined ctx

---

src/Client.js
src/lib/timing.js
src/server/meta/index.js

Gathers statistics on loading the initial state of
the app, which is before any of the API requests
have happened.
We send the data to hivemind which ends up logging to graphite something like
```
service_time.web.m2.server.shell.frontend.request:65.00005722045898|ms
service_time.web.m2.server.shell.frontend.response:0.9999275207519531|ms
service_time.web.m2.server.shell.frontend.dom_loading:83.9998722076416|ms
service_time.web.m2.server.shell.frontend.mount:90|ms
```
Note that we'll need to set the `process.env.ACTION_NAME_SECRET` in configuration for this to work.
👓 @schwers @phil303 @nramadas

Collect shell render RUM timings

---

src/routes.jsx
src/views/pages/BasePage.jsx

We may have data promises that lead to other data promises, which result
in multiple checks for `this.state.finished` when a page has finished
rendering. `this.setState` doesn't act immediately, so both checks will
see a false value, and we'll take page-finished actions twice. Instead,
we should check and set the state as an atomic operation.

Check and update state.finished atomically

---

src/server/meta/stats.js

This is a simplified version of what we do in 1X.
We use the fact that graphite buckets in 10s increments
and have the individual servers tell graphite about
their view of activeRequests counts.
👓  @schwers @nramadas @phil303

activeRequests tracking

---

.kage/manifests/deployment.yml

Rather than commit potentially sensitive secrets, tokens, headers, and URLs to public repos, we've broken configuration for staging environments out to config maps. This PR also makes the kage reddit-mobile staging environment more closely resemble the current staging environment's configs.
Since kage uses your local configs to determine how to carry out a staging deploy, you can still change values locally (without committing them) and staging the branch. For example, let's say I wanted to change my babel cache path. Here's the current value:
```
- name: BABEL_CACHE_PATH
valueFrom:
configMapKeyRef:
name: deployment-config
key: babel.cache.path
```
Here's an arbitrarily updated, un-committed change that I'm testing:
```
- name: BABEL_CACHE_PATH
value: /some/path
```
When you're done, …

Point kage deployment at a more thorough ConfigMap.

---

src/lib/loid.es6.js
src/routes.jsx
src/server/index.jsx

Through clever manipulation of 1X code (read: hacks and frustration), I think I have a solution for using api generated loids in 1X.
Essentially, I repurposed the current middleware used to create loids, and instead had the middleware yield on the route handling first so that the loids can be loaded by the api.
Blocked on: https://github.com/reddit/node-api-client/pull/151
:eyeglasses: @phil303 || @schwers || @uzi

Use loids generated by the api

---

src/lib/createCanonicalLinkFromState.js
src/server/templates/main.jsx

Add canonical link tags when the html is server-rendered. It only targets server renders because it assumes we don't need to worry about canonicals in non seo-bot situations.
:eyeglasses: @prashtx

Add canonical link tags when NOT shell rendering

---

blueprints.config.js
package.json
src/Client.js
src/app/actions/ads.js
src/app/reduxMiddleware/errorLogger.js
src/app/reduxMiddleware/index.js
src/app/router/handlers/CommentsPage.js
src/app/router/handlers/DirectMessage.js
src/app/router/handlers/Login.js
src/app/router/handlers/Messages.js
src/app/router/handlers/PostSubmit.js
src/app/router/handlers/PostsFromSubreddit.js
src/app/router/handlers/Register.js
src/app/router/handlers/UserProfile.js
src/app/router/handlers/handlerCommon.js
src/lib/eventTracker.js
src/lib/eventUtils.js
src/lib/isFakeSubreddit.js
test/lib/isFakeSubreddit.test.js

The pages this adds events to are the following:
- subreddits
- special subreddits (frontpage, all, etc)
- profiles
- messages
- login
- registration
- posting
This list is derived from Justin's comment on this [ticket](https://reddit.atlassian.net/browse/DA-638?focusedCommentId=55474&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-55474).
This does things differently than the original events patch. The original patch had middleware listening for `SET_PAGE`. The problem with this approach is that pages have very different field requirements. Sometimes the data for those fields wasn't even available unless it was asynchronously fetched for. The code was fast becoming a mess of special handling statements.
The approach this takes is to ask for the required …

Pageview events for most popular pages

---

blueprints.config.js
src/app/components/OverlayMenu/OverlayMenuRow.jsx
src/app/components/OverlayMenu/index.jsx
src/app/components/SettingsOverlayMenu/index.jsx
src/app/constants.js

This works by first settings the `mweb-no-redirect` cookie on click, and then
going to the www analogue of the current url using a normal anchor.
Assumptions:
- This assumes that the onclick handler fires synchronously before the browser
takes the user to the new location. From browser testing, this seems true.
Notes:
- Right now, we define the www url as separate than the m. url. Eventually,
when both clients are on the www urls, we can (if we wanted to - there might
be reasons not to) update this patch to just use the relative path.
This is semi-blocked on https://github.com/reddit/reddit-mobile/pull/730, which has some DefinePlugin updates. I could technically just add `REDDIT` to `process.env` right now but that'd result in a merge conflict. So I'll just wait. …

Get "go to desktop" working

---

blueprints.config.js
src/config.js

It's confusing to possibly have these types of fallbacks in two different places, so move them into config.js.

Keep the client definePlugin fallbacks in config

---

src/lib/apiOptionsFromState.js

The api expects loidcreated to be in UTC format, passing
unix time as we've been doing makes all of our server-side api
calls fail. This only really matters for googlebot right now,
hence why we didn't notice it sooner.
Test this by making a fake device profile in chrome with user agent 'googlebot', and making server side requests.
👓  @nramadas @uzi

Pass loidcreated cookie header in UTC format.

---

src/Client.js
src/lib/timing.js
src/server/meta/index.js

- Send timings based on the onLoad event.
- Detect if we're shell or seo rendered.
- Resolve the promise when we exit early.
- Make server and client messaging more clear.
Examples of data sent when we're shell rendered:
```
{ actionName: 'm2.server.shell',
startTiming: 0.02200007438659668,
requestTiming: 0.2989997863769531,
responseTiming: 0.002000093460083008,
domLoadingTiming: 0.09200000762939453,
mountTiming: 0.101 }
```
And when we're rendered for seo:
```
{ actionName: 'm2.server.seo',
requestTiming: 1.38100004196167,
responseTiming: 0.003000020980834961,
domLoadingTiming: 0.17599987983703613,
mountTiming: 0.378 }
```
👓 @schwers @nramadas @phil303

Rum timings refinement

---

blueprints.config.js
package.json
src/Client.js
src/Server.js
src/app/reduxMiddleware/errorLogger.js
src/lib/errorLog.js
src/server/meta/index.js
src/server/meta/stats.js

👓  @nramadas  @uzi  @phil303 
This patch is a start of making errors more useful in dev and production in mweb. My plan is to get this reviewed asap to find out pain points with this applied, and add more updates next week.
I'll roll the details into the commit body when review is finished, but at a high-level:
* Fixed an issue where client wasn't sending errors to the server `/error` endpoint. This prevented errors from being logged to the server logs, which in turn hides the errors from the log file.
* Fixed an issue where client errors weren't properly setting the `CLIENT|SERVER` env when formatting logs.
* Fixed an issue with parsing stack traces that prevent error messages from showing up.
* Fixed an issue where the `try/catch` handler in the stats timing middleware was preventing …

2x more verbose errors

---

src/lib/timing.js

Since we'll do a smaller launch of 2X initially,
we'll get numbers for all visitors instead of 10%
for now and scale back later if needed.
👓  @schwers @umbrae

Send timings data on all visits

---

src/lib/apiOptionsFromState.js

It's possible to have loid and not loidCreated cookies
from inbound requests. In fact, this will always be the
case when we have server-signed loids. This patch fixes
an exception when we try to call `toISOString()` on an
invalid date, that was being created because we passed the
default empty string value for `loidCreated` to the Date
constructor. In general, we just shouldn't pass the
cookie header if we don't really have a loidCreated anyway.
👓  @uzi

Don't pass loidCreated header if we don't have it.

---

src/Server.js
src/app/actions/apiRequestHeaders.js
src/app/reducers/apiRequestHeaders.js
src/app/reducers/apiRequestHeaders.test.js
src/app/reducers/index.js
src/config.js
src/lib/apiOptionsFromState.js
src/server/initialState/dispatchAPIPassThroughHeaders.js

This adds support for the env variables `API_HEADERS` and`API_PASS_THROUGH_HEADERS`. The former is a list of default key/value pairs to send as headers on server-side api requests. The latter is a list of headers to copy from the client request onto server-side api requests.
I included an update for the root cookie domain update we wanted to make. I can take it out if we want to get internal testing going asap, but if we like it and want to include it we'll have to get this puppet patch landed too: https://github.com/reddit/puppet/compare/master...schwers:2X-root-cookie-domain?expand=1 
👓  @phil303 @uzi

Update config and respect server headers

---

src/app/components/Comment/CommentDropdown/index.jsx
src/app/components/GoogleCarouselMetadata/index.jsx
src/app/components/Post/PostDropdown/index.jsx
src/app/components/SettingsOverlayMenu/index.jsx
src/app/components/UserProfileHeader/index.jsx
src/app/components/UserProfileSummary/index.jsx
src/app/pages/AppMain.jsx
src/app/pages/UserProfile/index.jsx
src/app/router/handlers/UserActivity.js
src/app/router/handlers/UserReroute.js
src/app/router/index.js
src/lib/createCanonicalLinkFromState.js

I've implemented this as additional valid urls in order to get this in and supported in a timely fashion.  The real thing we'll want to do of course is have the /u/* variants be 301 redirects to the /user/* ones, but this is a start.
I threw in a patch to change many of the /u/* links in the system to /user/* ones.  I'm not sure if we want any of these, but I at least wanted to call it out.
Also tossed in a small cosmetic issue while I was in the neighborhood.
👓 @schwers @phil303 @nramadas @umbrae

Support /user/* routes

---

src/lib/apiOptionsFromState.js

The value we get is from cookies, by default a string.
We don't have to send the ISO string anymore so there's
no reason to parse it, and circumvents an issue when
we tried to call the Date constructor on a unixtimestamp
string (it wants integers).
👓  @uzi

Don't parse loidCreated or pass it to Date constructor

---

src/app/components/PostSubmitModal/index.jsx

Problem:
Currently, self posts require both the title and the text field to be
filled. That's not an actual requirement and in fact, some subreddits,
like AskReddit require the text field to be empty.
Fix:
On self posts, just check for the subreddit and the title. For link
posts, continue to check for subreddit, title, and the link.
:eyeglasses: @schwers @uzi

Allow self posts to have empty text fields

---

src/server/meta/index.js

This lets us parse out the timings as well as
pase them in general.  In addition, the client
doesn't need to know.
👓  @schwers

Put timings messages on one line in the log

---

src/app/router/handlers/CommentsPage.js
src/app/router/handlers/PostsFromSubreddit.js
src/app/router/handlers/UserProfile.js
src/lib/eventUtils.js

- Profile page - handle an error where `name` is undefined. Occurs when
someone hits a profile page for a non-existent user.
- Comments page - handle an error where the post is undefined. Haven't
seen yet but it's probably possible so being defensive here.
- Listings page - handle an error where the listing page is undefined.
Occurs when a user doesn't have access to that subreddit.
Details:
If the important info is not present, return `null` in its stead. When
we're about to make the tracking call, check for `null` and if it
exists, don't make the call.
There might be more of these out there but I'll start with this as a foundation. 
:eyeglasses: @schwers @uzi @nramadas

Fix a few of event tracking errors

---

src/app/models/Session.js
src/server/meta/stats.js
src/server/session/loginproxy.js

👓  @phil303 similar to your patch, this will fix the server from throwing errors when the user enters a wrong password. The errors we get back from node-private seem to always be 'WRONG_PASSWORD' so I'm logging the error when it's anything _but_ that.

Stop loginproxy 401 from causing errors

---

src/lib/safeStringify.js
src/server/templates/main.jsx

There's a possible XSS vector via query parameters in the url and script
tags. So we need to escape them. We'll do this via their unicode escape
code.
I've added the `safelyStringifyData` function, which has a counterpart
in modmail and am running it against the json data before it's put into
the dom.
:eyeglasses: @nramadas

Sanitize json before putting it into the dom

---

src/Server.js

Enforce a same origin policy for frames (iframes, frames, or objects).
In other words, only hosts of the same domain as the app will be able to
serve it via an iframe. This prevents clickjacking based attacks.
The other options here are DENY or ALLOW-FROM <some origin>. The former
disallows the app from being displayed in iframes entirely, which feels
overly restrictive right now. The latter only allows the app to be
hosted by explictly selected domains, which we don't have a use case for.

Set X-Frame-Options to SAMEORIGIN

---

src/app/router/handlers/UserProfile.js

Fixes errors in the log like:
"Error: undefined is not an object (evaluating 'r.name')"
and
"Rejection: TypeError: undefined is not an object (evaluating 'r.name')"
👓  @phil303 @schwers @nramadas

Don't buildScreenViewData in UserProfile with no user

---

src/lib/createCanonicalLinkFromState.js
src/server/templates/main.jsx

In the case that we're rendering for SEO and they
were hitting a banned subreddit (or the like), we
were barfing on trying to get the cleanPermalink
(in the comments case).  Instead, when looking an
comments and listings of potentially banned subreddits,
we recognize that the data is missing and just don't
make the canonical links.
👓  @nramadas @schwers @prashtx

Don't produce a canonical when we're missing data

---

src/server/initialState/dispatchInitialCompact.js
src/server/initialState/dispatchInitialTheme.js
src/server/initialState/permanentCookieOptions.js
src/server/session/logoutproxy.js
src/server/session/setSessionCookies.js

All of our cookies were getting set with the `httpOnly` flag.
This was intended to increase security, but had the sideeffect
of preventing the client from updating cookies. A symptom of this
is your theme or compact preference not sticking. Session
cookies are still written with the `httpOnly` flag to protect
your tokens.
👓  @uzi @phil303 @nramadas

Make sure client can update cookies

---

src/app/reduxMiddleware/errorLogger.js
src/server/initialState/dispatchInitialCompact.js
src/server/initialState/dispatchInitialTheme.js
src/server/initialState/permanentCookieOptions.js
src/server/session/logoutproxy.js
src/server/session/setSessionCookies.js

The redux middleware error logger adds a property to errors,
to ensure they're aren't double logged. The property name was
`.caught` and we noticed some errors in the tap for trying
to set readonly properties, and traced it back to that line.
This patch attempts to fix this by using a more verbose, and
unlikely to be already present, property name.
👓  @uzi

Testout fix for 'can't set readonly properly' errors.

---

src/app/reduxMiddleware/errorLogger.js

This will make the ActionStack log full action objects for the `NAVIGATE_TO_URL` and `GOTO_PAGE_INDEX` action types. This should help us debug what's going on with the `HEAD` requests getting routed in through node-platform navigationMiddleware
👓  @phil303  @uzi

Log more info about navigation actions to debug HEAD issues

---

src/server/session/logoutproxy.js

👓 @uzi @phil303 
the second argument is the cookie value, the third is options. :(

Fix deletion of reddit_session cookie

---

src/app/components/Login/index.jsx
src/app/components/LoginRegistrationForm/Input.jsx
src/app/components/Register/index.jsx

Bug:
User was able to get passwords to autocomplete in plaintext by
originally typing them in with the "eyeball" enabled (makes password
input plaintext), logging out, going back to the login and enabling the
eyeball. Chrome would try to autocomplete his passwords.
Fix:
Make it possible to add the autocomplete attr onto the input dom nodes.
This works on [all mobile clients](http://caniuse.com/#search=autocomplete).

Add autocomplete attribute to LoginInput

---

src/app/reduxMiddleware/errorLogger.js
src/lib/errorLog.js

This tries to catch errors in setting a property on errors (which is for deduping error logs). If this works we might reveal a new error that's hidden behind the error for setting this property.
👓  @uzi @phil303

Don't fail on tagging errors, should reveal hidden errors

---

src/lib/gifToHTML5Sources.js

Should take care of a lot of the "Mixed content" warnings we get and be safer!

Convert imgur and giphy links to use https.

---

src/app/components/Comment/CommentTools/styles.less

Themed .icon:hover classes were overriding comment upvote and downvote
colors. This makes it so that upvoted and downvoted colors are applied
appropriately by following the same method the link uses - namely,
!important.
👓 @schwers

Fix coloring of upvote/downvote icons on :hover

---

src/app/components/cssCommons/PostAndCommentList.less
src/app/less/themes/nightMode.less
src/app/pages/UserProfile/styles.less
src/app/styles.less

Use a real black for the background color on most pages. It's better for battery life, is _actually_ darker in dark situations, like at night time, and I think it still looks good. Should probably be discussed with designers, but here's a PR just in case. Alternatively, we could detect android/ios and provide android only with the black, and gray everywhere else, but I don't feel strongly about keeping the gray vOv
Here's a couple screenshots, black first and then the current gray:
tldr: it may be very slightly less aesthetically pleasing, but it's more actually useful, and it saves battery on amoled screens.

Use true black for night theme

---

src/app/components/Post/PostContent/index.jsx

Without `e.preventDefault()`, nsfw links will open up in a new tab as
well as revealing the blurred image below.
👓 @schwers

Prevent nsfw show button from opening link

---

package.json
src/app/actions/mail.js
src/app/components/AppTopNav/index.jsx
src/app/components/MessageThread/Message.jsx
src/app/components/MessageThread/Message.less
src/app/components/MessageThread/index.jsx
src/app/components/MessageThread/styles.less
src/app/components/Messages/Comment.jsx
src/app/components/Messages/Message.jsx
src/app/pages/AppMain.jsx
src/app/router/handlers/Messages.js
src/app/router/index.js

Adds another page in which we display all of the
messages in a conversation. This is still read-only
support, but now the user should be able to see
everything at least.
Also guard the message endpoints against logged
out users while in the neighborhood
👓  @schwers @phil303

Add support for displaying message threads

---

src/app/components/CaptchaBox/styles.less
src/app/components/Dropdown/index.jsx
src/app/components/Dropdown/styles.less
src/app/components/DropdownCover/styles.less
src/app/components/OverlayMenu/styles.less
src/app/components/Post/PostHeader/styles.less
src/app/components/RelevantContent/styles.less
src/app/components/SubNav/styles.less
src/app/components/Toaster/styles.less
src/app/components/TopNav/styles.less
src/app/less/variables.less

This is a prep patch/hopeful cleanup for the way we handle z-indexes.
The goal is to have a finite and easy to remember amount of stacking
levels components can live at. This is to lower the chance of
unforeseen visual bugs future devs might run into. The z-indexes are
meant to be in a stacking context that is always relative to the dom
root and therefore easier to reason about.
Based on a 50 point scale - with the majority of components having 
the implicit z-index of 0 - the z-indexes of anything above the default 
are as follows (the higher in the list, the higher the stacking precedence):
- Toasters: 50
- Modals: 40    (Reporting, CaptchaBox)
- Nav Bar and menus: 30
- Dropdowns/tooltips: 20
- Opaque overlay: 10
This is meant to handle the most general cases, which is what our
current …

Normalize z-indexes across app

---

src/app/actions/reporting.js
src/app/actions/toaster.js
src/app/components/ModalSwitch/index.jsx
src/app/components/ReportingModal/index.jsx
src/app/components/ReportingModal/styles.less
src/app/components/Toaster/index.jsx
src/app/components/Toaster/styles.less
src/app/reducers/modal.js
src/app/reducers/toaster.js

I accidentally overwrote some of the changes that addressed PR
comments. I did this by force pushing without fetching my latest changes
done from another computer (hecka dumb). This undoes that mistake.
The one major change this adds back is some UI changes to the modal
recommended by Derek. Instead of a snoo icon with a green background,
it's now a flag with a yellow background.
This looks like this:

Reporting modal - fix accidentally reverted changes

---

src/app/components/Comment/index.jsx

Bug:
When a comment had no replies but needed a "load more" button, we were
not showing one. This was due a `replies.length` check that was
happening ahead of rendering the "load more" button.
Fix:
Allow the "load more" button to render independent of the length of
replies. This is done by making the `replies.length` check or'd with a
`loadMoreIds.length` check.
For comparison:
Before:
After:
Nested comments now have "load more" button as well:
:eyeglasses: @uzi || @schwers

Fix missing "load more" button

---

src/app/components/Comment/index.jsx

This is somewhat of a hack for the time being just to quiet the logs.
This field should have a default value of an empty array ideally. I'm
working on that version of the fix now, which will most likely be in 
api-client, but it's taking longer than expected.

Fix a missing `loadMoreIds` bug

---

src/app/components/Dropdown/styles.less

In order to create a new stacking context, `position: fixed` must be
used. This was using `position: relative`. This wasn't occurring on
desktop Chrome so I missed it unfortunately.
I tested this on ios browsers Chrome and Safari and desktop browsers
Chrome, Safari, and Firefox.
:eyeglasses: @nramadas

Fix z-index issue with dropdowns

---

Dockerfile.varnish
docker-compose.yml

By mounting the file we can guarantee that Docker doesn't cache the
config file (default.vcl) and will always use the newest one.
:eyeglasses: @spladug 
cc: @gtaylor @telaviv

Mount default VCL instead of copying over.

---

src/lib/formatDifference.js

The function signature for Date.setMinutes is
Date.setMinutes(min,sec,millisec), and
Date.getTimezoneOffset returns the value in minutes.
Therefore in California, being 7 hours off UTC at
the moment, the timezoneOffset is 420 minutes...
but if you put that as seconds, it ends up being
7 minutes.  Because of that, times being returned
by this library were off by 7 minutes.  Removing
the errant line fixes the problem.
👓 @schwers @phil303 
(It was bugging me that a brand new message or post said it was `7m` old... now it'll say `0m`.)

Small tweak to the formatDifference library

---

src/app/components/ErrorPage/index.jsx
src/app/components/ErrorPage/styles.less

This is for the case of an auth token refresh issue
that can occur if you require a refresh token on a
consecutive action on a page. This makes things
slightly friendlier to the user.
👓 @schwers @phil303 
What it looks like:

Add a "refresh this page" message to the ErrorPage

---

src/app/actions/posts.js
src/app/components/CaptchaBox/styles.less
src/app/components/DirectMessage/Composition.less
src/app/components/EditForm/styles.less
src/app/components/Toaster/styles.less
src/app/less/normalizers/redditReset.less

Seeing the toaster pop up on my iPhone 6, I felt like I was squinting
to read the text. Increasing the font-size up to 15px puts it at a
comfortable reading level. This is especially important with the
toaster because it auto-dismisses after 3 seconds.
I tested this down to iPhone 4 dimensions with some of the longer
messages. Sometimes the toaster text ended up taking 3 lines but still
looked pretty good even in those cases.
I removed the right padding on the text because there's already padding
around the close button to right, which was making it look like there
was too much padding in total between the two elements.

Increase toaster font size

---

src/app/components/CaptchaBox/styles.less
src/app/components/DirectMessage/Composition.less
src/app/components/EditForm/styles.less
src/app/less/normalizers/redditReset.less

iOS will automatically zoom in when an input is selected but not reset
the zoom level when the user is done. This allows for horizontal panning
which is not expected behavior from a UX perspective. (Also, it annoys
the crap out of me :P)
Rationale:
I'm normalizing all inputs because I'd never expect a dev of any
experience level to know/remember this while writing an input
component. By doing this everywhere, it's just taken care of. And b/c
it's css, it's easy to overwrite should the need arise.
It's pretty annoying that iOS forces this but it still looks pretty good
so I feel more ok making a universal rule. BUT in general, this kind of
thing screams "stop and think about what you're doing here" which is why
it's an RFC.
Details:
- This applies to text, number, and password inputs and …

Normalize all input font sizes to prevent zooming

---

src/app/pages/Comments.jsx
src/app/router/handlers/CommentsPage.js

If there is no subredditName in the urlParams, look up the
subreddit by postId, then fetch the recommended subreddit objects
These two urls should yield the same recommended subreddits:
[http://localhost:4444/r/relationships/comments/559d7x/this_is_a_difficult_question_to_ask_because_i_35m?feature_experimentrecommendedtopplain=#](http://localhost:4444/r/relationships/comments/559d7x/this_is_a_difficult_question_to_ask_because_i_35m?feature_experimentrecommendedtopplain=#)
[http://localhost:4444/comments/559d7x/this_is_a_difficult_question_to_ask_because_i_35m?feature_experimentrecommendedtopplain=#](http://localhost:4444/comments/559d7x/this_is_a_difficult_question_to_ask_because_i_35m?feature_experimentrecommendedtopplain=#)
👓 @uzi @phil303 @schwers

Experiment fix: look up recommended subreddits by postId

---

src/app/actions/posting.js
src/app/actions/reply.js
src/lib/eventUtils.js

Feature:
This adds comment events via the `reply` action and submit events via
the `submitPost` action.
Details:
- With comment events, you can have parent data values that are derived
from the OP's data or just a parent comment. There's some logic around
that.
- With post events, some keys change depending on whether a post is a
link or a self, so there's some logic around that as well.
- I noticed I was missing `base_url` in the `getBasePayload` function,
so I added that in.
Testing:
For comments, tested on replies to comments and posts and for posting,
tested on link and self posts.
I think you guys are doing the other events so eyeglassing you all.
:eyeglasses: @uzi @nramadas @ajacksified

Comment and post events

---

src/app/components/DropdownCover/styles.less

Thanks Apple. This is silly, but described by links like
http://stackoverflow.com/questions/3705937/
in which setting `cursor: pointer;`to the DropdownCover
tricks mobile safari into handling the click event...
you know, because it's not a touch event.
👓 @umbrae @phil303 @schwers

Make dropdowns close on IOS when clicking outside the menu

---

src/app/actions/overlay.js
src/app/actions/search.js
src/app/components/OverlayMenu/index.jsx
src/app/components/SearchBarOverlay/SearchBar/index.js
src/app/components/SearchBarOverlay/index.js
src/app/components/TopNav/index.jsx

The search event types are:
- `cs.search_executed`
- `cs.search_cancelled`
- `cs.search_opened`
Caveats:
In order to track search bar closing accurately, I needed a specific
"close search" action to fire. What was available to me was a more
generic action for closing the overlays. To get around this, I pass in
the "close search" handler from the SearchBarOverlay into the generic
OverlayMenu component. If the close handler from the outside props
exists then it uses that else it uses the generic one.
:eyeglasses: @nramadas || @uzi 
:eyeglasses: @drunken-economist

Add search events

---

src/app/actions/search.js

I missed this before I deployed the search events patch but for
consistency with the other client checks in the app, move this to
`process.env.ENV`.

move client check to process.env.ENV

---

blueprints.config.js
src/app/actions/ads.js
src/app/components/Ad/index.jsx
src/app/components/AdblockTester/index.jsx
src/app/components/AdsTracking/index.jsx
src/app/components/GoogleTagManager/index.jsx
src/app/components/PostsList/index.jsx
src/app/constants.js
src/app/index.jsx
src/config.js
src/lib/dom.js
src/lib/eventUtils.js
src/lib/frames.js
src/lib/gtm.js

Hey all, 
This Pr started out as porting GTM from 1x. Including `adblock` events seemed to make sense, as it's sort of related. Happy to break it out into two separate PRs. For ease of reviewing / reading I'll leave links to the individual commits so it's easier to tell whats-what (though it's probably best to leave comments on this PR itself vs the individual commits)
GTM notes: `frames.js` was copied wholesale from 1X, `gtm.js` and `dom.js` were copied as well but they have some minor cleanup.
GTM Patch [link](https://github.com/reddit/reddit-mobile/commit/8493ea7f6ce42812d48e43e84293ac3a8d1ce3e3)
[GTM Jira Mobileweb-492](https://reddit.atlassian.net/browse/MOBILEWEB-492)
Adblock Patch [link](https://github.com/reddit/reddit-mobile/commit/8493ea7f6ce42812d48e43e84293ac3a8d1ce3e3) …

Support GTM and adblock events

---

src/app/pages/AppMain.jsx
src/lib/gtm.js

Just some quick fixups:
1) GTM is proxies its event tracking through an iframe via `postMessage`, seeing some errors in the logs where `gtmIFrame.contentWindow` is undefined. I think this is either because the frame times out or the browser isn't letting us access the iframe. The latter might require more work so this is intended to be a stopgap for now so the logs are cleaner
2) The AppMain refactor made ErrorPages _not_ have a TopNav, second commit adds it back in.
👓  @uzi @phil303

2 x fixups

---

src/app/components/Post/PostHeader/index.jsx
src/app/router/handlers/UserReroute.js

So this seems like an unintended consequence of the u/ -> user/ redirect. By using setPage we don't call the handler on the server during a redirect, which is nice because we don't do extra work fetching anything, etc. However setPage doesn't run the handler, so OTOH(or the client) we don't run the handler, so you see broken user page. I would be open to just always using setPage and letting the handler run on the server, but I thought this was a good example for discussing platform in general, hence the large 👓  @uzi @ajacksified @nramadas @phil303 
Commit message:
We started redirecting `u/*` links to `user/*` because that's the cannonical
url. The redirect was using SET_PAGE, so on the client handlers weren't being
run. This made the user page sit idlely with a loading indicator …

Call UserActivity handler on the client for u/ links

---

src/lib/timing.js

This changes both the RUM timings and the handler
timings in with both will individually get a 10%
sample rate.
👓 @schwers @umbrae

Limit timings capturing down to 10% of users

---

package.json
src/app/reducers/posts.js

This patch solves two frequent instances of self text
and previews dissapearing. The first case is voting
on a selfpost often makes selftext disappear. This seems
like partially a bug from api-client, the version is bumped herein.
The other case is some api endpoints don't return the full media
preview. This mostly seems to impact NSFW posts returned by
the comments page api. You could see this when a NSFW post
had a preview in the listing, but lost it when going to the comments page.
Depends on https://github.com/reddit/node-api-client/pull/170
👓  @nramadas @phil303

Preserve dissapearing post selftext and previews

---

src/app/components/SettingsOverlayMenu/index.jsx
src/app/reducers/replyingComments.test.js

This was an oversight on the desktop redirect patch. The expiry is
currently just a session cookie. It needs to stick around for 1 year
for parity with the 1X implementation.
I also added a linter fix in `replyingComments.test`.
:eyeglasses: @uzi || @nramadas

Update expiry on desktop redirect cookie to 1 year

---

src/Server.js

This fixes a regression from 1X. When a user arrives via an m link url
and they have the mweb-no-redirect cookie, the most expected behavior
is to redirect to desktop, their preferred experience. We're currently
not respecting that preference.
Details:
This adds the redirect to `preRouteServerMiddleware`, which is where
we're doing all our global route handling. Just by virtue of the cookie
existing the redirect should happen. If it doesn't then continue on with
the mweb experience.
:eyeglasses: @nramadas || @uzi 
cc @powerlanguage

Add back the desktop redirect on mdot servers

---

src/Server.js

Currently we're just redirecting the frontpage of the desktop site
instead of redirecting to the desktop version of the page the user is
on. This adds the path to the redirect to fix this.

Add the correct path to desktop redirect

---

package.json

Rationale:
This no longer seems to be a dependency for 2X specifically. 
Testing:
I tested this by removing it from package.json, removing node_modules, and re-installing everything just to be extra sure it was gone. Then spot checking around the app and making sure no requests were failing.
:eyeglasses: @schwers @nramadas

remove superagent-retry

---

package.json
src/app/router/handlers/ReportHandler.js
src/app/router/index.js

This was a placeholder component from the no-js days. It's going unused
now so remove it from the codebase.
:eyeglasses: @nramadas

Remove unused ReportHandler and its endpoint

---

default.vcl
test/test_vcl.py

For all non-whitelisted 2X endpoints, we want to fallback to the desktop site.
:eyeglasses: @phil303 @schwers @uzi 
A few caveats:
- I can't test logged in behavior because login proxy isn't working for me
- We don't fall back to desktop for unsupported, deeper subreddit and user paths (e.g. `/u/wting/submitted`)
- This is a dev-only local change.

Add VCL rules for whitelisting valid 2X endpoints.

---

default.vcl

2X currently redirects /u/wting to /user/wting. Since that path isn't
whitelisted it results in showing the desktop version instead.
:eyeglasses: @schwers @prashtx

Whitelist /user/ for 2X.

---

src/lib/apiOptionsFromState.js
src/server/initialState/dispatchInitialUser.js

Two issues here:
0. We were comparing the `ms` value of the loidcreated we got back from the api to the ISO string version we had stored in the cookie. They obviously would not match, and so we were continuously re-writing the cookie. This in itself isn't that bad if we were constantly re-writing the same value. But we weren't. Because....
0. When sending the `loidcreated` cookie in the request, there was an extra `}` character in there. Which meant that the `loidcreated` we were sending the api was always invalid, so it was getting re-issued. FML.
:eyeglasses: @schwers @phil303

Fix loidcreated getting reset

---

src/app/reducers/replying.test.js

Bug:
One of the replying tests is currently broken due to my not using the
action creator. When I updated the payload in the action creator, I
forgot to update the payload in the test.
Fix:
Just use the action creator foo.

Fix broken reducer test

---

src/app/reducers/replying.test.js
src/lib/formatDifference.js

As a possible solution to the ambiguous "m" problem, this patch removes
the month abbreviation entirely. I chose this path for a few reasons.
1. The "mo" abbreviation looks weird to me (could just be me on this). 
Ex text would be:
- `r/foobarsub ● 5mo ● u/thephilthe`
2. The math for calculating the month was an approximation based on 30
day months, which seems too inaccurate.
3. Finally, native apps don't show months either and in my opinion, it
looks ok.
General notes:
I'm not entirely happy with this quick solution but I think it's better
than what we have. Looking around at how other apps handle this, most
seem to fallback to the full date text after a day or so, giving more
time info as more time goes by. Taking our example above, depending on
the "time ago" date, the text might look …

RFC: Remove month abbreviation

---

src/app/side-effect-components/SessionRefresher.jsx
src/lib/onVisibilityChange.js

Bug:
When a user has a reddit tab open and comes back to it some time later,
the session has expired. Any logged in action that user tries kicks them
to the register screen because our js doesn't know to try to update the
session. A user hitting refresh fixes that since the cookies are still
valid.
Fix:
This adds a visibility check that fires every time a tab is focused,
leveraging the [visibility api](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API), which is [well supported](http://caniuse.com/#search=visibilitychange) on mobile.
If the user had a refresh token and the token was expired, the
app will fetch a new one upon being focused again. This is a nice all
around solution since it avoids having to specially handle every logged
in action.
Caveats:
I've cleaned up …

Session refreshing on visibility changes

---

src/config.js

We currently default to 50 action steps logged. Since this exceeds our limits
per log line (4096 bytes), it truncates the log lines resulting in unparseable
JSON. As a result we can't programmatically analyze our error logs.
:eyeglasses: @schwers @uzi

Reduce number of actions logged.

---

src/app/actions/vote.js

Bug:
This copy was hardcoded to just 'comment' but the action applies to both
comments and posts. When something went wrong on a post upvote we'd show
"failed to upvote the comment", which makes no sense.
Fix:
Use the `type` (which is either 'post' or 'comment') in the copy.

Correct types on the error toaster

---

src/config.js
src/lib/createAmpHtmlLinkFromState.js
src/server/templates/main.jsx

For self post comments pages, we add a link tag with `rel="amphtml"` to
indicate to crawlers where they can find the AMP version of the page.
Because this is a crawler-targeted feature, we only need to do this for
compelte server renders.

Add amphtml link tags for self posts

---

src/app/actions/mail.js
src/app/components/MessageThread/index.jsx

It turns out that we can only reply to a message
thread if the other side has sent us a message.
For example, if there's one message in the thread
and the current user sent it, they can't send
further messages until the other side sends a reply.
Take a look at all of the messages in a thread, find
the latest response from the other side and use that
as the message id we respond to. Unfortunately the
API appears to succeed if we reply to our own message,
so this circumvents the issue.
We no longer show the replyToggle if the user can't
yet reply to a thread.
👓 @phil303 @schwers @andytuba 
And thanks @andytuba for helping diagnose this.

Fix message thread replying

---

src/lib/errorLog.js

I reverted the previous push because sometimes `stack` was undefined and caused these sorts of errors:
```json
{
"column": "12",
"env": "SERVER",
"isAPIFailure": false,
"line": "182",
"message": "Error: Cannot read property 'substring' of undefined",
"requestUrl": "/loginproxy",
"stack": "TypeError: Cannot read property 'substring' of undefined\n    at g (/opt/reddit-mobile/bin/webpack:/src/lib/errorLog.js:182:12)\n    at o (/opt/reddit-mobile/bin/webpack:/src/lib/errorLog.js:33:19)\n    at w (/opt/reddit-mobile/bin/webpack:/src/lib/errorLog.js:202:3)\n    at Object.<anonymous> (/opt/reddit-mobile/bin/webpack:/src/server/session/loginproxy.js:24:9)\n    at tryCatch (/opt/reddit-mobile-deps/regenerator-runtime/runtime.js:62:40)\n    at GeneratorFunctionPrototype.invoke [as _invoke] …
```

Handle when stack is undefined.

---

src/app/components/Messages/Header.jsx

This was previously working but hidden due to a
captcha-related issue. This should now be working,
so we can unhide the link.
👓  @phil303 @schwers

Enable showing the link to message compose

---

src/app/components/OutboundLink/index.jsx

The onTouchStart handler of the OutboundLinkComponent
wasn't passing the correct outboundLink. This should
have been tested more in Safari as well, but Android
Chrome was working fine, presumbably because its
events are more standardized.
👓  @nramadas

Fix outbound links in Safari

---

src/app/components/RelevantContent/index.jsx
src/app/pages/Comments.jsx

This is mostly just reverting an accidental deletion, but with a small
cleanup. It's possible to get a React exception if you don't return a
React element or null. This code has a code path that could possible
return undefined, which was sometimes causing an exception.
I've tested this and got it working under very select conditions, which
are:
1. User is logged out.
2. User has gotten to the comments page via a specific subreddit page
(not via the frontpage for example). The reason being that landing on
the subreddit page populates the necessary data for the relevant content
UX.
3. User has to have the "hot" sort set in the url (no other sorts work
by design looks like) when he hits the listing page. Hot just being on
by default doesn't seem to get this to show.
Talking with Andy, we're …

Add back in RelevantContent

---

src/app/components/SortAndTimeSelector/index.jsx
src/app/pages/AppMain.jsx
src/app/router/handlers/PostsFromSubreddit.js
src/app/router/index.js
src/app/sortValues.js

Bug:
Currently 2X doesn't support urls that have the format of `/r/nba/top`,
where the subreddit sort is part of the path. As part of the unified url
push, we need to support this.
Fix:
Currently we support the sort as a query parameter but we'd like to
deprecate this over time. So we're going to first look for the sort in
the url then fallback to the query param then fallback to 'hot'.
There's a few other sorts that 2X doesn't support yet at all, such as
"gilded" or "ads". Per discussion with William, we're going to 404 these
(this is the status quo).
Demo:
:eyeglasses: @nramadas @wting @schwers

Unified urls - Match subreddit sorts to desktop

---

src/app/actions/posting.js

👓 @schwers 
Seems like the post param was not set correctly.
I tried with this param name, and could see the
header `g-recaptcha-response`:
Thanks

Update post submit param name

---

src/app/components/InterstitialPromo/index.jsx

When a user follows the call to action from the cross-promotion
interstitial, we don't want to show them the promotion again. To satisfy
that, we set the flag to record that they've closed the promotional UI,
and then we navigate to the Branch link via javascript.

Record interstitial dismissal on navigation

---

src/app/actions/smartBanner.js
src/lib/eventUtils.js
src/lib/smartBannerState.js

We need to log a user preference change event when users dismiss the cross-promotional experiences. The event originally covered cookie-based preferences, but we're overloading it to include localStorage and other non-account preferences. We also use a different name for the preference on advice of DA, so that the field is more descriptive in our data pipeline. Changing the name we use inside the app would introduce some risk when migrating the old setting to the new name, which is not ideal while we have ongoing experiments related to this.

Issue an event when xpromos are dismissed

---

src/app/actions/smartBanner.js
src/lib/smartBannerState.js

Don't try to log a preference change event when the user follows the
link in the banner's call to action. We really just want to track when
users bail out of the crosspromo experience.

Log smartbanner preference change more carefully

---

src/app/components/InterstitialListing/common.jsx
src/app/components/InterstitialListing/styles.less

👓  @uzi or @prashtx 
There's been some feedback that the dismiss button on xpromo modals is hard to click on. This patch adds more padding to the link. It adds more padding to the bottom as the link is rendered near the bottom edge of the screen, and adding too much to the top could accidentally eat clicks intended for the app link button.

Add more padding to xpromo dismissal link

---

src/app/components/OutboundLink/index.jsx
src/lib/apiOptionsFromState.js
src/lib/findNearestLinkElement.js

This enables logged-out outbounds. The core feature work here is really simple, we now always send the `redditWebClient` queryParam.
This also fixes a critical bug in the OutboundLink component that prevented tracking clicks on links with nested dom elements. This slipped through QA as there's only one instance of this, but its an important one, the linkbar on comments pages.
👓  @curioussavage @nramadas

Enable logged-out outbounds

---

src/app/featureFlags.js

As a temporary measure, we are showing the list/subreddit treatments
(frontpage/listings experiments) also to users bucketed into the control
groups. We want to continue to get bucketing events, so we know when a
user has been exposed to this feature, and we want to show 100% of users
the select treatments. We can't eliminate control groups in the API's
bucketing mechanism, so we use this workaround instead.

Turn select xpromo variants to 100%

---

src/app/actions/smartBanner.js
src/app/components/InterstitialListing/index.jsx
src/app/components/InterstitialListing/modal.jsx
src/app/components/InterstitialPromo/index.jsx
src/app/components/XPromoWrapper/index.jsx
src/app/reducers/smartBanner.js
src/app/reducers/smartBanner.test.js

We need to support display of the cross-promo interstitials for the
appropriate pages for in-app navigation, but we also don't want to show
multiple interstitials per session (and in particular not for sequential
navigations). We track if we have already shown an xpromo experience,
and then we can avoid showing it for later pages.

Support xpromo interstitials for in-app navigation

---

src/app/constants.js
src/app/featureFlags.js
src/lib/createAmpHtmlLinkFromState.js
src/lib/getContentIdFromState.js
test/lib/getContentIdFromState.test.js

Create a basic page-bucketing mechanism, so we can restrict a feature to
a percentage of content. This is a temporary mechanism and not a
full-fledged page-based experimentation/flagging framework.
Restrict the amphtml link tag to just 2% of content, so that not all of
our self posts show up in search results as their AMP'd versions.

Restrict the amphtml link tag to 2% of content

---

src/app/components/Comment/CommentDropdown/index.jsx
src/app/components/Comment/CommentTools/index.jsx
src/app/components/Comment/index.jsx
src/app/components/Dropdown/index.jsx
src/app/components/Dropdown/styles.less
src/app/components/Post/PostDropdown/index.jsx
src/app/components/Post/PostFooter/index.jsx
src/app/components/Post/index.jsx

Previously, we were using a tooltip to show
actions like save, report, etc. We are moving
towards a new design that utilizes modals
instead, to make it easier to implement mod
tools with updated design in the future.
https://reddit.atlassian.net/browse/CE-353

Change Post tool display

---

src/Server.js

In the past we only checked the presence of the cookie rather than the value. As a result, when we zero out the cookie it still redirects users.
:eyeglasses: @andytuba @schwers @telaviv

Check redirect cookie's value.

---

src/app/actions/posts.js
src/app/components/Post/PostContent/index.jsx
src/app/components/Post/index.jsx
src/app/components/Post/mediaUtils.js
src/app/reducers/index.js
src/app/reducers/playingPosts.js
src/app/reducers/playingPosts.test.js
src/lib/eventUtils.js

[CONT-4](https://reddit.atlassian.net/browse/CONT-4)
**issue:**
This pull request resolves the issue caused by gifs playing when users go back to the previous page. example: from a comment page back to a listing page where they had previously expanded several posts. The problem is all the gifs playing at once use up a lot of data and slow things down.
**solution:**
playing state was moved out of the postContent component into redux and also decoupled from expanded state.
**bonus:**
this lets us keep playing the gifs seamlessly when a user taps on the comments page link after playing the gif (only relevant platforms like android that play video/gifs inline).
**concerns:**
1. since moved out the only state in postContent it was expedient to convert it to a pure functional component. This …

Playing state gif 

---

package.json
src/lib/eventUtils.js

Platform will now send a value indicating when the
user navigated directly to the site. We also now handle
internal navigation by building the referrer from the
current url/domain
**Solution**
I modified the function that initializes the currentPage for the 'first' page (the second on the stack technically) which sends a string indicating there was no referrer, we can then look for that in eventUtils and distinguish between empty referrer on first load vs on single page app routing changes.
**issues**
I get errors but I think they are related to running off a local version of @r/platform. if you have a local copy of platform set up please test. Otherwise we need to get someone who has it working correctly to test.
for [CONT-5](https://reddit.atlassian.net/browse/CONT-5) together with …

Send correct referrer with events

---

src/app/components/Post/PostContent/index.jsx

problem: while in playing state gif posts had the image rendered behind the playing gif. Also images were being rendered with both the image tag and the css background image. 
solution: We now don't change playing state for things that are not playable. We also check to make sure we are not playing before rendering the preview image as a background image.
👓 @schwers

Fix duplicate images being rendered behind gifs while playing

---

package.json
src/app/components/Post/PostContent/index.jsx
src/app/components/Post/PostContent/styles.less
src/app/components/Post/PostHeader/index.jsx
src/app/components/Post/PostHeader/styles.less
src/app/components/Post/index.jsx
src/app/components/Post/mediaUtils.js
src/app/components/PostsList/index.jsx
src/app/pages/Comments.jsx
src/app/pages/PostsFromSubreddit.jsx

JIRA Ticket: https://reddit.atlassian.net/browse/CE-152
As part of integrating spoilers into mweb we decided to refactor the NSFW flow to leverage the new obfuscated image previews returned by the r2 api (especially since we are looking to deprecate the `nsfw` key from the api response). Spoilers will follow the exact same pattern as NSFW images and posts on mweb.
**Screenshots**
*Listing View*
*Listing Expanded View*
*Comments Page*
*NSFW and Spoiler*

Spoilers and NSFW Refactor

---

src/app/components/Post/PostContent/index.jsx

nsfw gifs and media from gfycat were not getting obfuscated correctly, this patch fixes the issue and presents the obfuscated media preview as the thumbnail. 
cc: @powerlanguage

Fix nsfw preview image obfuscation from gfycat

---

src/server/session/logoutproxy.js

We are having a cookie persistence error on mweb. Essentially, when a user logs out, then navigates to a subreddit, the `token` cookie becomes populated with that user's old cookie, which logs them back in.
This is especially problematic when a user (`user1`) logs out, then logs in on an alt (`user2`), then navigates to a subreddit and is unknowingly logged in as `user1` again.

Clear 'token' cookie on logout

---

src/app/actions/hidden.js
src/app/actions/saved.js
src/app/components/Post/PostDropdown/index.jsx
src/app/components/Post/PostFooter/index.jsx
src/app/components/PostAndCommentList/index.jsx

The two issues addressed here are
1. Make the hide toggle button say unhide for hidden posts.
2. Filter out the hidden saved posts from the main comments/posts store by the hidden/saved flags
so they get removed from the list when the user unhides/saves them.
in response to issue reported here: https://www.reddit.com/r/mobileweb/comments/5ir1uy/we_cant_unhide_posts_we_are_only_ever_given_a/
Was an easy fix so I jumped on it, and included some refactoring.

Fix text for unhide and make hidden list responsive

---

src/Server.js
src/app/actions/modTools.js
src/app/actions/user.js
src/app/router/handlers/handlerCommon.js

👓 @schwers @birakattack 
You can test on https://modtool-fixup-1.mobile.staging.snooguts.net (note that production cache behavior is different on staging so you can't actually repro the problem -- I am basically making sure that the cache headers don't crash anything or log people out unexpectedly).
Note that on staging, when you navigate to `r/pics` (for example) via the url (not inside the app), you get logged out. This is old behavior, not introduced by this change.
I also added some checks to `fetchModeratingSubreddits` to avoid API calls.

Modtool fixup 1

---

src/app/components/ReCaptcha/index.jsx
src/app/components/Register/index.jsx

When a user gets form errors when trying to register an account, the captcha that they created is no longer valid. However, we don't prompt them to re-do the captcha and get re-issued a valid `gRecaptchaResponse` to pass to the api.
This patch will cause the recaptcha to reset if the user had errors while trying to create an account.
NOTE: This isn't a _fantastic_ product solution since this potentially forces the user to have to do the captcha verification more than once. In an ideal world, we would validate the form first, and if everything looks ok, ask the user to verify through recaptcha. However, what's in this patch is a quick fix that will restore the ability for users to register.

Force the captcha to reload on registration errors

---

src/app/actions/modTools.js
src/app/reducers/moderatingSubreddits.js
src/app/reducers/moderatingSubreddits.test.js

For users who are moderators on >100
subreddits, the fetch pagination returns
two apiResponses, which was causing a bug
when attempting to get apiRespose.status.
Instead, we will now only capture errors,
as we don't really need the apiResponse code

Fix modTool apiResponse status bug

---

src/lib/eventUtils.js

This adds the following pieces of data to the xpromo payload:
`target_id`
`target_fullname`
`listing_name`
`target_sort`
`target_count`
`target_filter_time`
`target_before`
`target_after`
👓  @uzi @prashtx @arjunb023

Add additional payload data to xpromo.

---

src/app/featureFlags.js

In testing https://github.com/reddit/node-api-client/pull/187, I noticed what seems to be a bug in bucketing events. `app/featureFlags` was adding a `user_id` field on its events, but it's not using any of the common event payload code. As a sideffect, it's not generating the save `user_id` value as the other events are. 
This patch pulls in `getUserInfoOrLoid` to do that work. I'm not sure what fields are expected on the `bucketing` events, but it might be better to use `getBasePayload`
👓  @telaviv @nramadas @curioussavage

Use eventUtils to generate user info on bucketing events

---

blueprints.config.js
package.json
src/app/featureFlags.js
src/lib/eventTracker.js
src/lib/objectToHash.js
src/server/meta/index.js

This is the first in a series of payload optimizations. 
For an overview (@madbook, this should help explain @curioussavage's patch) please see: https://github.com/schwers/reddit-mobile/pull/3 
* note: these numbers are somewhat outdated as there has since been additional commits to mweb, and we're now including raven. 
👓  @curioussavage (cc @madbook, @birakattack)
The first commit in this patch sets us up to do analysis step by step, and have a visualization to guide our efforts.
The second commit is "the low hanging fruit" of potential optimizations we can make.
Before and After:
* 357 KB gzipped -> 264 KB gzipped
* 1.3 MB -> 1017 KB
This work, and the rest of the work in the bundle audit can be visualized with `webpack-bundle-analyzer`. With the first commit you can run `npm run …

Begin payload reduction

---

src/app/reducers/visitedPosts.js
src/app/reducers/visitedPosts.test.js
src/lib/getDeviceFromState.js
src/lib/getSubredditFromState.js

This removes some unneeded lodash code in the payload.
Before and After (from Chrome Network tab):
* 985KB         -> 967KB
* 255KB gzipped -> 250KB gzipped
👓  @curioussavage

Convert extraneous lodash imports to lodash-es.

---

src/app/components/CommentTree/index.jsx

:eyeglasses:  @phil303 
Looks like `process.env.ORIGIN` is not set for the client bundle so it defaults to the dev url. I think it makes more sense not to worry about origins since the platform redirect action handles relative links.

Comments: use relative link for continue thread redirect

---

src/app/components/CommentTree/index.jsx

👓  @schwers 
This was an oversight from the flat comments pull request. The loading spinner currently renders forever on pages with no comments.

Only show loading spinner while comments request is pending

---

src/apiClient/apiBase/Model.js
src/app/actions/commentsPage.js
src/app/components/CommentTree/index.jsx
src/app/pages/Comments.jsx
src/app/reducers/helpers/stickyCommentsFromState.js
src/lib/getContentIdFromState.js
src/lib/getSubredditFromState.js
test/lib/getContentIdFromState.test.js
test/lib/getSubredditFromState.test.js

Noteable changes:
* Updates access to `state.comments` and `state.commentsPages`
* Fix api model toJSON serialization that was causing some
Javascript errors on full (seo) renders. `uuid` and `type`
weren't being serialized properly. This could affect
SEO crawlers that run JavaScript.
* Fix `undefined` in href's on continue thread / more comments
links
* Fixes tests

Fix a few comments bugs from state and seo.

---

src/lib/smartBannerState.js

The Reddit Android app expects `reddit://` url scheme links to start with `reddit`. Adding a new `$android_deeplink_path` attr to our branch links with that prefix makes the deep links work as expected.
There's a test version of this with comments xpromo enabled at: https://android-deeplinks.mobile.staging.snooguts.net/
👓 @prashtx

Fix branch links to support android deep linking

---

src/Client.js
src/app/actions/ads.js
src/app/actions/commentsPage.js
src/app/actions/postsList.js
src/app/reducers/commentsPages/api/index.js
src/app/reducers/postsLists.js
src/app/reduxMiddleware/errorLogger.js
src/app/router/handlers/CommentsPage.js
src/app/router/handlers/PostsFromSubreddit.js
src/lib/adblock.js

We've seen an increase in 404's, and bug reports of 'not found' pages. 404's are now down in grafana after https://github.com/reddit/reddit-mobile/pull/1030 was merged. But there are continued reports of bad pages. 
Noteable fixes:
* listing and comments pages should now always dispatch `success` or `failed`, this should ensure we always update the status code properly.
* errorLogger middleware is updated to ensure we properly log comments page failures
* ads requests  aren't made on the server, and as failsafe the adblock check shortcircuits on the server. (this came up in testing SEO renders)
* client's sentryOnError is defaulted to a no-op for dev mode
👓 @curioussavage @prashtx @dwick

Record more status codes

---

src/app/actions/accounts.js
src/app/models/AccountRequest.js
src/app/reducers/accountRequests.js
src/app/reducers/accountRequests.test.js
src/app/reducers/loid.js
src/app/reducers/loid.test.js
src/lib/eventUtils.js
src/server/initialState/dispatchInitialUser.js

There's a fairly frequent 'invalid time' exception being thrown in
`dispatchInitialUser`, that has the effect of returning no content
and issuing 404s. This seems to be often be associated with a
`FAILED_ACCOUNT` action on the redux stack for Googlebot.
So it's possible they're coming in with an invalid loidcreated cookie
that's causing `Date` to throw.
This patch:
* tracks account request failure status, and doesn't set loid
cookies when there was a failure.
* doesn't set loid cookies if the `me` account request failed
* adds try/catch w/logging when doing loidcreated conversion
* fixes a bug in reducers/loid that was using 'loid' and 'loidcreated'
from any recevied account (it should only be checking accounts.me)
👓  @prashtx @curioussavage

Gracefully handle failed accounts and invalid loidCreated.

---

src/server/initialState/dispatchInitialUser.js

👓  @prashtx I realized that some users will have these set from fastly, this is an intermediate measure to convert to ISO

Convert epoch millisecond loidCreated

---

src/apiClient/apis/SavedAndHiddenCommon.js
src/apiClient/apis/SearchEndpoint.js
src/app/components/Post/PostHeader/index.jsx

We recently started using the post model's subredditDetail object to
generate subreddit/profile links and labels for PostHeader. If the post
doesn't have a subredditDetail object, we fall back to the prior method
of using the subreddit name that gets passed in.
Include the `sr_detail=true` parametery on a couple of more API
requests, so that we have access to the subreddit details when possible.

Use subreddit details only when available

---

src/apiClient/apis/AccountsEndpoint.js
src/app/components/SortAndTimeSelector/index.jsx
src/app/reducers/subreddits.js
src/app/reducers/subreddits.test.js
src/app/router/handlers/UserActivity.js
src/app/router/handlers/UserProfile.js
src/lib/eventUtils.js

Call out to track page events for the profile posts-activity and
comments-activity screens.
Capture the profile-subreddit data that arrives via account requests.
Add target_sort, target_filter_time, is_contributor, and screen_name
fields to the profile screenview payloads.
Fix the navigation targets for the comments-activity sort selector.
Add the `t2_` prefix for profile (account) screenview target_fullname
values.

Profile screenviews

---

src/apiClient/models/Subreddit.js

makeUUID() can be called from a few places. In some cases,
we have the server response, and in others an already
cleaned object.  Unfortunately, there's a difference
between "display_name" and "displayName", which was
causing us to set the model's uuid to `undefined`
whenever we'd toggle the subscription.  Instead, if
we already have a uuid, just use that.
👓  @schwers @prashtx

Fix toggling subscription

---

src/app/components/DualPartInterstitial/styles.less

👓  @curioussavage @tomsoir 
This fixes a bug in firefox, where the dual part interstitials duplicate listing is not being clipped. This results in a second listing being rendered without a background, offset from the pages primary listing. 
e.g.
[source](https://www.reddit.com/r/softwaregore/comments/5zinoy/great_new_mobile_reddit_feature_get_twice_the/)

Fix content-clipping bug in firefox

---

src/app/components/Comment/CommentDropdown/index.jsx
src/app/components/MessageThread/index.jsx
src/app/components/Post/PostFooter/index.jsx

A recent patch (c249ea6fe21efc5630b4ae8f01e5000cb73d083b),
changed account uuids to be lowercased, to fix some
issues when comparing the url name to the received account name.
As a side-effect this disabled editing and deleting of comments
for some accounts, and a few other edge cases.
This patch simply calls toLowerCase for those comparisons.
Adding to lowercase in the models would break username display.
👓  @madbook @prashtx

Use author.toLowerCase when comparing against logged in username.

---

package.json
src/app/router/handlers/PostsFromSubreddit.js

If users or bots make a request for a profile subreddit, we want to
redirect them to the corresponding profile. The underlying subreddit is
just an implementation detail and should not be exposed via the UI.
For bots, we need to issue a 30x redirect status code, so crawlers know
that this is not meant to be an indexed page. We are defaulting to 302
right now but should probably change this to 301 in the future, so we
send a stronger signal that the content should not be indexed at the
original "subreddit" URL.
For regular browser requests and in-app navigation, we will know that
this is a user subreddit on the client, so we issue an in-app navigation
to the corresponding profile page URL.

Redirect requests for profile subreddits

---

src/app/components/CommunityOverlayMenu/index.jsx

Looks like 0242da273fa20fe6a2f491590a308a0b3e581e7a introduced some linter errors that are causing new builds to fail linting (e.g. https://travis-ci.org/reddit/reddit-mobile/jobs/213859601)
👓 @luisatlive

Fix linter errors in CommunityOverlayMenu

---

src/config.js

Had to add the `www` to the placeDomain for use in the place postMessage.

Fix origin for postMessage on place

---

src/app/actions/loid.js
src/app/reducers/loid.js
src/app/reducers/loid.test.js
src/lib/apiOptionsFromState.js
src/server/initialState/dispatchInitialUser.js

We need the API to have any edgebucket cookie we may have received
upstream, which it will use along with the loid cookie, if present.

Pass the edgebucket cookie along with API requests.

---

src/app/pages/UserActivity/index.jsx
src/lib/getSubredditFromState.js

The problem appears after navigation from the comments page (to index page,
for example). In this case, when you request a subreddit name, it will be
returned from the last visited comment page.

Fixing of "current" key-param in a Comments page

---

src/app/featureFlags.js

Render the amphtml link tag for all self post comments pages rather than
just 2%.  By doing the same on desktop, we will let crawlers find and
index the AMP version of all of our self post comments pages.

Serve amphtml link data for all self posts

---

src/apiClient/models/PostModel.js
src/app/actions/ads.js

👓  @jamesmaa 
Already added support for this on r2 desktop. This adds it for mweb.

Add support for arbitrary trackers

---

src/app/pages/UserActivity/index.jsx
src/app/pages/UserProfile/index.jsx

If a user is a contributor, we need to ensure that their user
subreddit data is available before we can determine if the profile is
NSFW. We also need to look for the user subreddit data in state using
the correct casing, since we key off of lowercased subreddit names.

Wait on user subreddit to determine NSFW status

---

src/app/components/DualPartInterstitial/Header/styles.less

Fix top content padding in XPromo post preview

---

src/app/actions/optOuts.js
src/app/components/SettingsOverlayMenu/index.jsx
src/app/reducers/optOuts.js
src/app/reducers/optOuts.test.js
src/app/reducers/toaster.js

https://reddit.atlassian.net/browse/CHAN-673
In additional: 
— a new menu notification component that is displayed when clicking the OptOuts link.
— now this option optOut works without any URL parameters (?)
PS to toggle the OptOut flag you can use this url-flag:
http://localhost:4444/?no_xpromo_interstitial_menu=false

Add notification modal component for the OptOut menu link

---

src/app/components/HTML5StreamPlayer/index.jsx

This prevents all videos within a feed from all loading at the same time in card view. This was reviewed in reddit-mobile-private and tested there. We are just cherry picking the commit over to deploy.
:eyeglasses: @MoMitch

Fixed offscreen videos buffering on initial load

---

src/app/components/HTML5StreamPlayer/index.jsx
src/app/components/HTML5StreamPlayer/styles.less
src/app/components/Post/PostContent/index.jsx

Initialize scrub thumb position on HTML5StreamPlayer scrub start.
Reduce state dependencies in the HTML5StreamPlayer component (state updates occur as needed but current state is retrieved from video tag where possible).
Add additional loading checks incase initial load fails.
Align scrub track to player buttons

Check and load HLS video if initial load failed (expando/hidden etc.) + UI bugfixes

---

src/apiClient/models/PostModel.js
src/app/router/handlers/CommentsPage.js
src/lib/getSubredditFromState.js

Fetch a bit of the crosspost data info into the
Post model. For now in the interest of time, we're
not bothering to process the data.
If said data exists, then we add it to the screenview
event when viewing a post comments page.
👓  @prashtx @schwers @nramadas

Add crosspost data to screenview events

---

src/app/components/BannerAd/index.jsx
src/app/pages/Comments.jsx
src/lib/dfp.js

ticket: https://reddit.atlassian.net/browse/ADS-1909
Currently this doesn't have support for some params that r2 uses (`subreddit`, `SIS_category`, etc.), but the docs amazon passed me seem incomplete and I'm not sure how we're supposed to do that with a SPA. r2 passes them via `apstag.init`, which can only be called once. I'll reach out and fix that up if possible. This should still work however.

Add amazon a9 header bidding

---

src/lib/dfp.js

👓 @griffinmichl 
from mike:
> Since you are not using setdisplaybids and are manually managing the bids, you need to pass the amznsz value to us. The DFP LI is expecting amznsz=320x50 so right now we are not passing any bid values.
> Please make a small code change on your end to handle the new amznsz param (to handle the new orders). This is what you have currently:
> ["amznbid", "amzniid"].forEach(function(e) {
> Please change that to:
> apstag.targetingKeys().forEach(function(e) {

a9: Ensure all targeting kvps are passed to gpt

---

src/app/components/HTML5StreamPlayer/index.jsx
src/app/components/Post/PostContent/index.jsx
src/app/components/Post/postUtils.js

Show the reddit video player even if user has ‘Don't show thumbnails next to links’
Remove the fullscreen custom controls and instead let android native controls take place (Makes the app simpler for third party apps to view).
Provides a fix for issue MEDIA-388:
https://reddit.atlassian.net/browse/MEDIA-388

Set reddit native video to ignore thumbnail user setting

---

package.json

👓 @arjunb023 @mlburgos 
cc @wting 
https://reddit.atlassian.net/browse/GROW-828
> However, we noticed that you have a cached version of our web SDK on your own servers. We’d politely ask that you update your cache with the latest version of our SDK found here: https://cdn.branch.io/branch-latest.min.js. If you don’t update, you could potentially jeopardize the value of Branch substantially if you’re still using the old version of the SDK when iOS 11 is released in the second week of September.
They have this lib in npm package already, so woohoo
The change is one liner and I double check branch-latest.min.js has the same web2.25.2 lib inside and there were no API change on new versions of the lib.

Update branch.io lib for better support of iOS11 deep links

---

src/Client.js
src/Server.js

This disables mobile-web error reporting to Sentry. The goal
was to make the smallest change necessary to make sure errors
weren't being reported anymore as mobile-web is currently not
being actively worked on and existing errors, which make up
a disproportional amount of error-reporting traffic, are not
being addressed. This should allow for quick re-enabling in the
future if desired.
:eyeglasses: @phil303 @curioussavage

Remove raven middleware from client and server applications

---

src/app/less/mixins/table.less

This sets tables to display in inline-block mode so we
can set a max width. Tables will scroll horizontally now

Fix page width issue with wide tables

---

src/app/components/Post/PostHeader/index.jsx

👓 @dwick 
Locked comments currently show the locked icon twice. Once on the left side of the header and once on the right. Confirmed with Jamie he wants to remove the one on the left side (to match the native apps).

Only show locked icon once per post
