- index.js
- src/config.es6.js
> Remove keys from client config

- src/server.jsx
> Add security headers

- package.json
- src/oauth.es6.js
> Such oauth many security wow

- src/views/components/Listing.jsx
Prevents framed sites from busting the frame or opening popups, like we do in https://github.com/reddit/reddit/blob/master/r2/r2/templates/innertoolbarframe.html#L42
> Add `sandbox` attribute to off-site iframes

- assets/js/client.es6.js
- src/app-mixin.es6.js
- src/server.jsx
- src/views/pages/index.jsx
:eyeglasses: @btholt or @danehansen
> Load in routes *after* mutator plugins

- assets/less/components/TopSubnav.less
- assets/less/components/dropdown.less
- assets/less/components/grid.less
- src/app-mixin.es6.js
- src/lib/titleCase.es6.js
- src/redirects.jsx
- src/routes.jsx
- src/views/components/CommentPreview.jsx
- src/views/components/Dropdown.jsx
- src/views/components/Listing.jsx
- src/views/components/SortDropdown.jsx
- src/views/components/UserActivitySubnav.jsx
- src/views/components/UserProfile.jsx
- src/views/components/UserProfileNav.jsx
- src/views/pages/index.jsx
- src/views/pages/userActivity.jsx
- src/views/pages/userGild.jsx
- src/views/pages/userProfile.jsx
First pass on user profile. Needs some design work on the tabs and the overview page.
Waiting on API changes from @kemitche to access trophies without oauth tokens.
:eyeglasses: @danehansen, @btholt
> User profile first pass

- src/views/layouts/DefaultLayout.jsx
A tremendously complex and involved PR
:eyeglasses: @btholt or @danehansen
> Set script to async

- assets/less/base.less
- assets/less/components/buttons.less
- assets/less/components/comment.less
- assets/less/components/listing.less
- assets/less/components/text.less
- assets/less/variables.less
- src/views/components/Comment.jsx
- src/views/components/CommentBox.jsx
- src/views/components/Listing.jsx
- src/views/pages/index.jsx
- src/views/pages/listing.jsx
Not fully ready yet, but I wanted you two to start looking at it.
:eyeglasses: @ajacksified @danehansen
> Comment page rework

- .eslintrc
- assets/less/components/listing.less
- src/views/components/Listing.jsx
- src/views/components/PlayIcon.jsx
- src/views/components/SVG.jsx
- src/views/components/SideNav.jsx
- src/views/components/TopNav.jsx
:eyeglasses: @ajacksified @btholt
> Fix video and preview sizing and add play icon

- assets/js/client.es6.js
- package.json
- src/routes.jsx
- src/server.jsx
- src/views/components/TrackingPixel.jsx
- src/views/pages/index.jsx
- src/views/pages/listing.jsx
- src/views/pages/userActivity.jsx
- src/views/pages/userGild.jsx
- src/views/pages/userProfile.jsx
Also did a little cleanup.
:eyeglasses: @btholt or @danehansen 
Don't merge until https://github.com/reddit/reddit-public/pull/3411 (add "Access-Control-Expose-Headers" to responses, which will let us actually read the XHR headers we need)
> Embed tracking pixel from api headers

- assets/less/components/SideNav.less
- assets/less/components/TopNav.less
- assets/less/components/comment.less
- assets/less/components/listing.less
- assets/less/variables.less
- src/views/components/Comment.jsx
- src/views/components/Listing.jsx
:eyeglasses: @danehansen or @btholt 
Fixes:
* Expand area under top bar to vertical height of 36px (currently at 30)
* List view headlines should be 18px Arial regular (appearing 14px bold on iOS)
* Subreddit titles should be Arial regular (currently Arial bold)
* Remove self.subreddit text from all list view posts
* Reduce vertical space between list item entries from 19px to 8px
* Remove stroke from edge of burder menu
* OP's username should be in bold rather than have blue box around it
> Style polish

- assets/less/components/TopSubnav.less
- assets/less/components/listing.less
- assets/less/components/text.less
- assets/less/components/twirly.less
- assets/less/variables.less
- src/views/components/Comment.jsx
- src/views/components/DownvoteIcon.jsx
- src/views/components/Listing.jsx
- src/views/components/UpvoteIcon.jsx
:eyeglasses: @danehansen or @btholt 
Fixes:
* Vote Icons large and clipped - should be 16px height & weight, color #dedede
* Down arrow by "hot" should be pointed down and centered horizontally
* List view meta-information should be limited to one line of text and fade to white if it extends past one line
* Meta-information text should be all Arial regular #919192
* Dotted graphic artifacts appearing by expanding comment button
* Timestamps on comments should be reduced (3h, not 3 hours ago, etc - as in list view)
* Mods green, admins red, special dark-red
> Design polish

- package.json
- src/redirects.jsx
- src/routes.jsx
- src/views/components/CommentPreview.jsx
- src/views/components/Listing.jsx
- src/views/components/ListingDropdown.jsx
- src/views/components/TopNav.jsx
- src/views/components/TopSubnav.jsx
- src/views/pages/index.jsx
- src/views/pages/listing.jsx
- src/views/pages/userActivity.jsx
Also remove leading / from /r/ and /m/ and /u/ and whatnot. And get rid of /u/.
:eyeglasses: @danehansen or @btholt or @jo-asakura
> Support multis

- assets/less/components/TopNav.less
- src/views/components/ListingDropdown.jsx
- src/views/components/TopNav.jsx
- src/views/components/Vote.jsx
:eyeglasses: @btholt @ajacksified
> Add beta banner to top nav

- src/views/components/Listing.jsx
> Fix issue where videos would occasionally have too much top padding

- package.json
- src/server.jsx
- src/views/components/Comment.jsx
- src/views/components/CommentBox.jsx
- src/views/components/Vote.jsx
- src/views/pages/listing.jsx
:eyeglasses: @btholt or @jo-asakura or @danehansen
> Voting and commenting

- assets/js/client.es6.js
- src/routes.jsx
- src/server.jsx
- src/views/components/TrackingPixel.jsx
- src/views/pages/index.jsx
- src/views/pages/listing.jsx
- src/views/pages/userActivity.jsx
- src/views/pages/userGild.jsx
- src/views/pages/userProfile.jsx
:eyeglasses: @ThorArakis and [ @btholt or @jo-asakura  ]
> Add logged-out user tracking cookie

- src/views/components/Dropdown.jsx
- src/views/components/ListingDropdown.jsx
> Open options on click; close other dropdowns when one opens

- assets/less/components/SVG.less
- assets/less/components/listing.less
:eyeglasses: @jo-asakura or @ajacksified
> Fix svg cropping issue

- assets/less/components/TopSubnav.less
- assets/less/components/twirly.less
- assets/less/variables.less
This reverts commit 9e3e2bc89b8b192ff4883905a5c59e84f4f3fa19.
:eyeglasses: @jo-asakura or @ajacksified
> Revert "Always point arrow down"

- assets/js/client.es6.js
- src/lib/danehansen/Utils.es6.js
- src/views/components/Dropdown.jsx
> Fix dropdown open/close bug and touch detection

- assets/less/components/SideNav.less
:eyeglasses: @jo-asakura or @ajacksified
> Put shadow back on SideNav

- assets/less/components/search.less
- src/routes.jsx
- src/views/pages/search.jsx
> Fix for the search prev.button; styling issues

- src/views/components/TopNav.jsx
- src/views/pages/userActivity.jsx
- src/views/pages/userGild.jsx
- src/views/pages/userProfile.jsx
:eyeglasses: @danehansen or @ajacksified
> Fixes failing user page link

- assets/less/components/SearchBar.less
- assets/less/components/search.less
- src/views/pages/search.jsx
> Search input nozoom

- src/server.jsx
> Misc https fixes

- assets/less/components/alerts.less
- assets/less/components/search.less
- assets/less/components/text.less
- assets/less/fancy.less
- assets/less/variables.less
- src/oauth.es6.js
- src/routes.jsx
- src/views/pages/login.jsx
- src/views/pages/register.jsx
:eyeglasses: @kemitche @JordanMilne @jo-asakura @danehansen
> Registration

- src/config.es6.js
- src/routes.jsx
- src/views/components/TopNav.jsx
- src/views/layouts/DefaultLayout.jsx
> Canonical link

- assets/js/client.es6.js
- src/app-mixin.es6.js
- src/oauth.es6.js
- src/routes.jsx
- src/server.jsx
- src/views/components/CommentBox.jsx
- src/views/components/TopNav.jsx
- src/views/pages/index.jsx
- src/views/pages/listing.jsx
- src/views/pages/search.jsx
- src/views/pages/subredditAbout.jsx
- src/views/pages/userActivity.jsx
- src/views/pages/userGild.jsx
- src/views/pages/userProfile.jsx
Depends on https://github.com/reddit/snoode/pull/16.
:eyeglasses: @jo-asakura 
Also notifying @rram
> Pass useragent through to snoode per request

- index.js
- package.json
- src/app-mixin.es6.js
- src/server.jsx
:eyeglasses: @jo-asakura
Notifying @rram
> Allow adding extra default snoode headers

- src/oauth.es6.js
> Set api headers and user agent for auth requests

- src/routes.jsx
- src/views/components/SideNav.jsx
- src/views/components/TopSubnav.jsx
- src/views/components/UserActivitySubnav.jsx
> Hide login buttons

- assets/js/client.es6.js
- package.json
- src/app-mixin.es6.js
- src/oauth.es6.js
- src/routes.jsx
- src/server.jsx
- src/views/components/Comment.jsx
- src/views/components/CommentBox.jsx
- src/views/components/Listing.jsx
- src/views/components/SideNav.jsx
- src/views/components/TopNav.jsx
- src/views/components/TopSubnav.jsx
- src/views/components/UserActivitySubnav.jsx
- src/views/components/Vote.jsx
- src/views/pages/index.jsx
- src/views/pages/listing.jsx
- src/views/pages/search.jsx
- src/views/pages/subredditAbout.jsx
- src/views/pages/userActivity.jsx
- src/views/pages/userGild.jsx
- src/views/pages/userProfile.jsx
:eyeglasses: @ajacksified and I guess @xilvar
> Refactor api access

- index.js
- src/routes.jsx
:eyeglasses: @jo-asakura 
Notifying @rram and @spladug - will allow additional config
> Add config for pass-through headers

- src/routes.jsx
- src/views/components/Listing.jsx
- src/views/pages/index.jsx
- src/views/pages/listing.jsx
- src/views/pages/search.jsx
- src/views/pages/userActivity.jsx
> Set https config directly to props

- src/views/components/Listing.jsx
I think it should do it :smile:
> Add protocol check for GIFs

- src/views/components/Listing.jsx
:eyeglasses: @ajacksified or @danehansen
> Add media.oembed under protocol check as well

- assets/less/components/text.less
- src/routes.jsx
- src/views/components/Listing.jsx
- src/views/pages/listing.jsx
:eyeglasses: @danehansen or @jo-asakura
> Add more options to listing to allow for sponsored posts.

- src/views/components/Listing.jsx
Don't merge until we get the all-clear from @xiongchiamiov.
:eyeglasses: @jo-asakura or @danehansen
> Use image previews instead of full-resolution

- src/views/components/Listing.jsx
> Fix: Links in texts posts don't work

- assets/js/client.es6.js
- src/routes.jsx
- src/server.jsx
- src/serverRoutes.es6.js
- src/views/layouts/DefaultLayout.jsx
- src/views/pages/error.jsx
- src/views/pages/faq.jsx
- src/views/pages/index.jsx
- src/views/pages/listing.jsx
- src/views/pages/search.jsx
- src/views/pages/subredditAbout.jsx
- src/views/pages/userActivity.jsx
- src/views/pages/userGild.jsx
- src/views/pages/userProfile.jsx
:eyeglasses: @jo-asakura 
Notes:
Putting together the title in the router is kind of messy, since data is loaded in the view. I plan on refactoring data gathering *back* to the router, which cleans this *and* a lot of other inconsistencies. Since title/meta is really only important for server rendering, and it mostly works on the client, this is good enough to cover use cases until I get a chance for the big refactor.
> So meta even this acronym

- assets/js/client.es6.js
- assets/less/components/SideNav.less
- assets/less/components/listing.less
- public/img/placeholder.svg
- src/constants.es6.js
- src/routes.jsx
- src/server.jsx
- src/views/components/Listing.jsx
- src/views/components/SideNav.jsx
- src/views/layouts/BodyLayout.jsx
- src/views/pages/index.jsx
- src/views/pages/search.jsx
- src/views/pages/userActivity.jsx
:eyeglasses: @jo-asakura or @ajacksified
> Implement compact view

- src/views/components/Listing.jsx
- src/views/components/SideNav.jsx
- src/views/pages/index.jsx
- src/views/pages/userActivity.jsx
> Fix mispelling

- src/constants.es6.js
:eyeglasses: @danehansen @ajacksified
> Add TOP_NAV_HEIGHT to constants

- assets/less/components/listing.less
- src/views/components/Listing.jsx
> Replace XXX icon with NSFW text

- assets/less/components/listing.less
> Fix iOS NSFW warning

- assets/js/client.es6.js
> load es5-shims from cdn

- src/serverRoutes.es6.js
> No user crawling

- assets/js/client.es6.js
- src/oauth.es6.js
- src/routes.jsx
- src/server.jsx
Uses the refresh token to be able to keep a user logged in indefinitely.
:eyeglasses: @danehansen @curioussavage
> Auto-refresh expired tokens

- README.md
- src/views/pages/faq.jsx
Changes to the docs explaining that node_modules should be on the PATH.
Changes to the FAQ- Just grammar and typos.
> Docs and FAQ Changes

- assets/js/client.es6.js
- src/constants.es6.js
- src/views/components/Listing.jsx
- src/views/components/ListingList.jsx
- src/views/pages/index.jsx
- src/views/pages/listing.jsx
- src/views/pages/search.jsx
- src/views/pages/userActivity.jsx
> Implement lazy loading on listings

- src/serverRoutes.es6.js
- src/views/layouts/DefaultLayout.jsx
@ajacksified Sorry for the trouble, apparently I'm still learning when it comes to the "advanced" stuff of Git.
[This is from the previous pull request](https://github.com/reddit/reddit-mobile/pull/134), but with just one commit, and no mess :+1: 
Thanks for the help by the way!
> Add support for iOS/Android's "Add To Homescreen".

- src/oauth.es6.js
- src/routes.jsx
- src/server.jsx
Move loading data onto the request cycle so that data can be updated. Also refactor gathering data for pages into a series of promises, which allows for multiple simultaneous API requests, which should help out performance significantly.
:eyeglasses: @danehansen @curioussavage
> Refactor loading data; get user info on request if missing

- assets/js/client.es6.js
- index.js
- src/lib/timing.es6.js
- src/routes.jsx
- src/serverRoutes.es6.js
This will post the initial server render timings to statsd (via hivemind.)
> Send server render times to tracking server

- src/views/components/SideNav.jsx
> Prevent body from scrolling while SideNav is open

- assets/js/client.es6.js
- src/routes.jsx
- src/views/components/BetaBanner.jsx
- src/views/components/MobileButton.jsx
- src/views/components/SideNav.jsx
- src/views/pages/error.jsx
> Set cookie on return-to-desktop

- assets/less/components/Dropdown.less
- assets/less/components/Loading.less
- assets/less/components/SVG.less
- assets/less/components/SideNav.less
- assets/less/components/TopNav.less
- src/constants.es6.js
- src/views/components/Logo.jsx
- src/views/components/MobileButton.jsx
- src/views/components/SVG.jsx
- src/views/components/icons/CheckmarkIcon.jsx
- src/views/components/icons/HamburgerIcon.jsx
- src/views/components/icons/RIcon.jsx
- src/views/components/icons/SearchIcon.jsx
- src/views/components/icons/SnooIcon.jsx
- src/views/components/icons/TwirlyIcon.jsx
> Make future svg backup css easier

- index.js
- src/routes.jsx
- src/server.jsx
- src/views/components/TrackingPixel.jsx
- src/views/pages/index.jsx
- src/views/pages/listing.jsx
- src/views/pages/search.jsx
- src/views/pages/subredditAbout.jsx
- src/views/pages/userActivity.jsx
- src/views/pages/userGild.jsx
- src/views/pages/userProfile.jsx
:eyeglasses: @umbrae 
Now with configuration to build experiments.
Next step: build out or use a real testing framework. For now, this works well enough.
> Set up A/B test for compact vs list view

- src/oauth.es6.js
Something that `node-oauth2` is doing is incompatible with our `refresh_token` implementation. :mystery:
:eyeglasses: @curioussavage or @danehansen 
Now, when you expire, a refresh token should be automatically requested on your behalf and it should succeed. Previously, it was getting `400`s back.
Testing: set the `tokenExpires` to now + 1 minute.
> Manual refesh_token request

- src/oauth.es6.js
- src/server.jsx
:eyeglasses: @kemitche and @JordanMilne and @curioussavage
> Convert reddit.com session to m.reddit.com session

- assets/js/client.es6.js
- assets/js/trackingEvents.es6.js
- assets/less/components/SideNav.less
- assets/less/components/forms.less
- src/routes.jsx
- src/serverRoutes.es6.js
- src/views/components/SideNav.jsx
It amazes! It astounds! It's the...
Magical go-to input box!
It handles input such as:
* r/whatever and /r/whatever
* u/whatever and /u/whatever
* unprefixed text - it tries to load a subreddit, and if that fails, it sends the user to search. Amazing!
* If a matching subreddit isn't found, it sends the user to search. Astounding!
> Add smart "go to" field in side nav

- assets/js/client.es6.js
- package.json
- src/server.jsx
- src/views/components/BetaBanner.jsx
- src/views/components/SideNav.jsx
Fixes an issue where compact settings were forgotten.
> Refactor cookie get/set, use client cookies on client

- src/views/components/ListingList.jsx
- src/views/components/SearchBar.jsx
- src/views/pages/search.jsx
> Search cleanup

- src/views/components/Vote.jsx
> Only color vote arrow if user is logged in

- assets/js/client.es6.js
- assets/less/components/component-animations.less
- assets/less/components/forms.less
- assets/less/components/listing.less
- package.json
- src/views/components/Comment.jsx
- src/views/components/Listing.jsx
- src/views/components/ListingDropdown.jsx
- src/views/components/MobileButton.jsx
- src/views/components/ReportPlaceholder.jsx
Depends on https://github.com/reddit/snoode/pull/23
> Add link reporting

- src/views/components/ListingDropdown.jsx
> Clicking the report form shouldn't close the dropdown

- src/routes.jsx
- src/views/components/Comment.jsx
- src/views/components/Listing.jsx
- src/views/components/ListingDropdown.jsx
- src/views/components/SortDropdown.jsx
- src/views/components/TopSubnav.jsx
- src/views/pages/index.jsx
- src/views/pages/listing.jsx
:eyeglasses: @curioussavage or @danehansen 
Automatically opens / highlights the permalink'ed comment. Adds a 'permalink' option to the comment menu. Respects `context=N` querystring.
> Implement comment permalinks

- assets/js/client.es6.js
- src/views/components/SideNav.jsx
> Add ref source to "view desktop" link

- assets/less/components/listing.less
- src/views/components/ListingDropdown.jsx
> Listing page improvements

- assets/less/components/comment.less
- assets/less/components/text.less
> Fix Firefox word breaking

- src/views/components/SearchBar.jsx
- src/views/pages/search.jsx
> Make search work with broken/disabled js

- src/server.jsx
- src/views/pages/listing.jsx
- src/views/pages/search.jsx
- src/views/pages/subredditAbout.jsx
This makes sure that the error logs get good contextual information. It also makes it so that when an auth call fails, it doesn't log the user out.
> Proper error tracing on API error

- assets/less/components/listing.less
NSFW "Show Post?" box styles were inconsistent across devices, should be
fixed now.
> Consistent Styles

- assets/less/components/SVG.less
- assets/less/variables.less
- src/routes.jsx
- src/views/components/Comment.jsx
- src/views/components/Listing.jsx
- src/views/components/ListingDropdown.jsx
- src/views/components/ListingList.jsx
- src/views/components/SideNav.jsx
- src/views/pages/userSaved.jsx
Does not include a "saved" or "hidden" page on user profile yet.
:eyeglasses: @danehansen or @curioussavage 
depends on https://github.com/reddit/snoode/pull/25
> Implement save and hide.

- assets/less/components/SideNav.less
- src/views/components/CommentPreview.jsx
- src/views/components/ListingList.jsx
so hacky
:eyeglasses: @danehansen and @curioussavage 
maybe also @DorianGray in case he knows a better way to get the sub name hnggg
> Fix subreddits not showing up on user activity pages

- assets/less/components/Listing.less
> Fix newly introduced Listing footer css bugs

- src/app-mixin.es6.js
- src/routes.jsx
- src/server.jsx
- src/views/components/GoogleCarouselMetadata.jsx
- src/views/pages/listing.jsx
Big blob of metadata for googlebot.
:eyeglasses: @curioussavage or @danehansen and @xilvar
> Add metadata for google carousels

- assets/less/components/ListingContent.less
- assets/less/mixins.less
> Make mixins for flex-box

- assets/less/components/aspect-ratio.less
- src/views/components/ListingContent.jsx
> Fix animated gif play icon bug

- buildTasks/js.js
- package.json
- src/server.jsx
Sneak in an Android 2.3 fix too.
> Disable compactTest when finished.

- assets/less/components/Listing.less
- assets/less/components/ListingContent.less
- assets/less/components/comment.less
- src/tweenDefault.es6.js
- src/views/components/Comment.jsx
- src/views/components/Listing.jsx
- src/views/components/ListingContent.jsx
- src/views/components/ListingList.jsx
- src/views/components/SideNav.jsx
> Abstract tweening to/from auto

- src/views/components/Comment.jsx
- src/views/components/Vote.jsx
Score wasn't being updated when upvoting/downvoting comments. This fixes that and some issues with the localScore calculation in Vote.jsx.
> Update score when voting on comments

- assets/js/client.es6.js
- src/views/pages/search.jsx
- src/views/pages/submit.jsx
> Use app.redirect everywhere; also fixes goto

- src/views/components/ListingContent.jsx
> Put catch in place for nsfw unexpanded posts to display placeholder

- src/views/components/Comment.jsx
> Remove transition from closing comments

- package.json
> Update snoode version

- assets/less/components/Listing.less
- assets/less/components/SideNav.less
- src/views/components/Comment.jsx
- src/views/components/ListingContent.jsx
- src/views/components/SideNav.jsx
> Enabled compact view image expanding

- src/views/components/TopNav.jsx
:eyeglasses: @danehansen  or @ajacksified 
had to adjust this some more since some subs were not being caught due to the minimum length
> Adjust max subreddit title display length

- assets/less/components/TopNav.less
- src/views/components/TopNav.jsx
> Replace subreddit shortening with css solition

- src/views/components/Loading.jsx
- src/views/components/TopNav.jsx
- src/views/components/icons/RainbowSnooIcon.jsx
- src/views/components/icons/SnooIcon.jsx
> Create rainbow snoo

- src/views/components/Ad.jsx
- src/views/components/ListingContent.jsx
- src/views/components/ListingList.jsx
Can you test this on staging please?
> Fix ad images not always loading due to race condition

- assets/less/components/Listing.less
- assets/less/components/TopNav.less
- src/views/components/Listing.jsx
- src/views/components/ListingList.jsx
- src/views/components/TopNav.jsx
- src/views/components/icons/PostIcon.jsx
> Fix Listing stacking bug

- assets/less/components/ListingContent.less
- src/views/components/Listing.jsx
- src/views/components/ListingContent.jsx
> Fix nsfw image bug

- buildTasks/js.js
- package.json
> Fix sourcemaps

- src/routes.jsx
:eyeglasses: @ajacksified this allows for non-default api endpoints (using a local dev version of reddit)
> Pass oauth origins to client

- assets/less/components/Dropdown.less
- gulpfile.js
- src/views/components/Dropdown.jsx
- src/views/components/icons/CheckmarkIcon.jsx
:eyeglasses: @ajacksified & @curioussavage I haven't tested this yet because my shit is broken but just alerting you guys that I have this in the works. It should reduce mounted components on all our dropdown components, which in the case of the home page and subreddit pages, could produce some noticeable savings.
> Remove invisible mounted components from Dropdown

- src/views/components/icons/CommentIcon.jsx
- src/views/components/icons/FlagIcon.jsx
- src/views/components/icons/MailIcon.jsx
- src/views/components/icons/NSFWIcon.jsx
- src/views/components/icons/PostIcon.jsx
- src/views/components/icons/SeashellIcon.jsx
- src/views/components/icons/ShareIcon.jsx
- src/views/components/icons/SnooIcon.jsx
- src/views/pages/userGild.jsx
- src/views/pages/userProfile.jsx
> Improve performance on svg components

- assets/less/components/ListingContent.less
- assets/less/components/TextSubNav.less
- assets/less/components/icon-font.less
- public/img/placeholder-text.svg
- src/views/components/Listing.jsx
- src/views/components/ListingContent.jsx
Jira 209
Feel free to make a less terrible icon if you want.
> Make compact selftext expandable

- src/serverRoutes.es6.js
- src/views/layouts/DefaultLayout.jsx
It doesn't play well with tabs and can be awkward to use for a very external-link-heavy application like this.
Jira 188
:eyeglasses: @danehansen
> Remove manifest.json

- src/views/components/ListingContent.jsx
> Allow links in selftext preview to pass through

- src/lib/mobilify.es6.js
- src/views/components/GoogleCarouselMetadata.jsx
Fix it so that m.reddit.com shows up in search results.
:eyeglasses: @danehansen
> Use m.reddit.com urls in google carousel data

- assets/js/client.es6.js
- assets/less/base.less
- assets/less/components/SVG.less
- assets/less/components/badge.less
- assets/less/components/messages.less
- src/routes.jsx
- src/views/components/Inbox.jsx
- src/views/components/MessageNav.jsx
- src/views/components/MessagePreview.jsx
- src/views/components/SideNav.jsx
- src/views/components/TopNav.jsx
- src/views/pages/messageCompose.jsx
- src/views/pages/messages.jsx
:eyeglasses: @danehansen @curioussavage
> Messaging; all except compose

- src/views/pages/subredditAbout.jsx
Quick fix for this page, an undefined `props` var was being referenced.
> Fix for subreddit about page

- assets/less/components/SideNav.less
- src/views/components/AutoTween.jsx
- src/views/components/SideNav.jsx
> Fix SideNav tweens

- src/views/pages/submit.jsx
pressing enter while choosing a subreddit would submit the form. this was really no point to having this there anyways
> remove onSubmit from post submit form

- src/views/components/UserProfile.jsx
- src/views/pages/userActivity.jsx
- src/views/pages/userGild.jsx
- src/views/pages/userProfile.jsx
- src/views/pages/userSaved.jsx
> Remove reduntant userProfile object

- src/views/components/SideNav.jsx
> Fix SideNav subreddit dropdown bug

- src/views/components/ListingContent.jsx
> Fix compact thumbnail click area

- assets/js/client.es6.js
- package.json
- src/lib/savedReply.es6.js
- src/routes.jsx
- src/views/components/Comment.jsx
- src/views/components/CommentBox.jsx
- src/views/pages/BasePage.jsx
- src/views/pages/error.jsx
- src/views/pages/faq.jsx
- src/views/pages/index.jsx
- src/views/pages/listing.jsx
- src/views/pages/login.jsx
- src/views/pages/messageCompose.jsx
- src/views/pages/messages.jsx
- src/views/pages/register.jsx
- src/views/pages/search.jsx
- src/views/pages/submit.jsx
- src/views/pages/subredditAbout.jsx
- src/views/pages/userActivity.jsx
- src/views/pages/userGild.jsx
- src/views/pages/userProfile.jsx
- src/views/pages/userSaved.jsx
:eyeglasses: @danehansen @curioussavage 
Got sucked into a rabbit hole while working on the error stuff, there's a few random commits in here too.
relies on https://github.com/reddit/horse/pull/5
> rabbit holes

- src/views/components/Ad.jsx
:eyeglasses: @JordanMilne 
on https://m.staging.wireddit.com/
> Fix ad response encoding

- assets/js/trackingEvents.es6.js
- src/views/components/MessagePreview.jsx
not sure if GA is the thing to use for pageviews but to my knowledge we don't have anything else right now
> add GA events for message reply and pageview

- assets/js/client.es6.js
Track the time it takes React to mount and send it to our rum endpoint.
> Add mountTime to rum timings

- src/views/components/Ad.jsx
- src/views/components/ListingList.jsx
- src/views/pages/index.jsx
State shouldn't be in global app state, or globals at all. This fixes loids; the rest will be fixed soon.
:eyeglasses: @zeantsoi @curioussavage
> Use props.loid rather than app.state.loid

- assets/less/components/comment.less
> comment: fix overflow issue, clean up some css

- assets/less/components/Loading.less
- assets/less/components/comment.less
Any other small fixes I should sneak into this?
> Perf followup

- src/views/components/SideNav.jsx
Looks like one more thing slipped through.
I am assuming this data-no-route attr is something the koa router looks for?
> SideNav: fix login and logout links

- assets/js/client.es6.js
- src/server.jsx
We're already registering in app-mixin, so this is unnecessary (and wasting cpu.)
https://github.com/ajacksified/reddit-mobile/blob/ee68de25914a44dae566c58365a38d522f7a7852/src/app-mixin.es6.js#L21
> Don't register routes twice

- assets/js/client.es6.js
- src/views/layouts/DefaultLayout.jsx
Accidentally using the wrong property to load GA.
> Swap "propertyId" for "googleAnalyticsId"

- index.js
- src/routes.jsx
- src/views/layouts/DefaultLayout.jsx
> V3 cleanup

- src/routes.jsx
> Build options with deepassign instead of nested assigns

- src/views/pages/BasePage.jsx
:eyeglasses: @curioussavage or @umbrae
> Add "compact" prop to tracking pixel

- src/views/pages/BasePage.jsx
> Use ctx.referrer for tracking pixel

- src/routes.jsx
- src/views/pages/BasePage.jsx
Fixes routes which are undefined on mobile web.
> 404 catchall

- assets/js/client.es6.js
- src/app-mixin.jsx
- src/server.jsx
To be replaced by real 'RouteNotFound' error handling Soon
> Load routes.jsx last

- src/routes.jsx
this fixes route changes between multis and home
> IndexPage: change key to use title

- src/serverRoutes.es6.js
> Filter 404 catch-all route from /routes

- src/views/components/GoogleCarouselMetadata.jsx
- src/views/pages/listing.jsx
> Fix props beings sent to google carousel metadata

- src/lib/mobilify.es6.js
- src/views/components/Comment.jsx
> Run `mobilify` on comments

- assets/less/components/Submit.less
- src/views/components/SearchBar.jsx
- src/views/components/SubredditSelectionButton.jsx
- src/views/pages/search.jsx
> Submit search on "submit", not text entry

- package.json
- test/index.js
- test/lib/formatDifference.es6.js
- test/lib/titleCase.es6.js
- test/views/components/Modal.jsx
Ok I added mocha and chai/sinon along with jsdom. Not really tied to that if you want to do something else, but it is working fine.
I could probably improve the tests but I just wanted to get it set up with some examples in the repo so anyone can start adding tests.
> Testing: set up mocha and chai, add some example tests

- src/oauth.es6.js
In particular, lacking scopes for subscribe, privatemessages, report, and edit were missing and breaking functionality for some users.
We may want to come up with a strategy for nuking login cookies after this goes live to help everyone along.
:eyeglasses: @curioussavage @umbrae
> Request ALL the scopes

- src/views/pages/listing.jsx
> Remove duplicate `key` assignment

- src/oauth.es6.js
- src/server.jsx
:eyeglasses: @curioussavage or @umbrae 
This makes it so that if we change oauth scopes in the future, we can invalidate existing login cookies. (Like https://github.com/reddit/reddit-mobile/commit/73c9b73d2b8b36f060e9b844cbf33472e6474374)
> Scopes cookie

- README.md
> Add `npm link` and oauth config info to readme

- gulpfile.js
- index.js
- package.json
- version.js
> Version gate node version

- assets/js/client.es6.js
- src/oauth.es6.js
- src/server.jsx
:eyeglasses: @curioussavage, and also @JordanMilne for visibility 
Don't use an invalid, cloudflare'd CSRF token on timings.
> Ignore CSRF on /timings

- src/oauth.es6.js
- src/server.jsx
:eyeglasses: @umbrae 
Thanks for the pointer, @kjoconnor
> Revert token-nuke and get all scopes by *

- src/sideNavAboutMenuItems.es6.js
- src/views/components/SideNav.jsx
- src/views/layouts/BodyLayout.jsx
a few small changes to SideNav for readability too
sidenav: Doesn't rely on the datacache for subscriptions (the pr moving cache to snoode broke subscriptions in the menu), user and subscriptions are passed as props
Also pulled the data for the about reddit links into another file, saved about 70 lines :)
> SideNav: don't rely on datacache for user or prefs

- src/views/components/ListingDropdown.jsx
:eyeglasses: @madbook 
low hanging fruit. 
https://reddit.atlassian.net/browse/MOBILEWEB-134
> Comment: remove 'more from' from comment menu

- assets/js/client.es6.js
- index.js
- src/app-mixin.jsx
- src/config.es6.js
- src/lib/errorLog.es6.js
- src/server.jsx
- src/views/components/Comment.jsx
- src/views/components/Interstitial.jsx
- src/views/pages/listing.jsx
Together with https://github.com/reddit/hivemind/pull/21 and https://github.com/reddit/horse-react/pull/6 (both merged now)
:eyeglasses: @curioussavage or @umbrae 
This first pass sets us up to log to statsd (hivemind) and gets us ready for more complicated logging (winston, probably.) This also changes the `debug` config to `debugLevel`.
Note: error functions had to be defined three times; as early as possible for uncaught exceptions, and again with more detail within the app, which should give us decent traces.
> Global error logging; first pass, sends to statsd.

- src/routes.jsx
- src/views/components/Listing.jsx
- src/views/pages/userSaved.jsx
- test/index.js
- test/views/components/Listing.jsx
- test/views/pages/userSaved.jsx
:eyeglasses: @madbook @ajacksified 
other than all the es5 to es6 cleanup noteworthy items are:
userSaved: I refactored it a little while testing and had to refactor listing to get it working again.
> Fix hidden

- CONFIG.md
- assets/js/trackingEvents.es6.js
- package.json
- src/config.es6.js
:eyeglasses: @umbrae @curioussavage 
Refactors event tracking a bit, and adds in the event-tracker to send data to the events collector.
> Event tracking

- src/server/oauth.es6.js
- src/views/components/ListingContent.jsx
> Check for `oembed` in ListingContent aspectRatio

- src/views/components/Listing.jsx
> Fix missing domain bug on listing footer

- src/server/index.jsx
https://github.com/reddit/horse-react/pull/8
As a side effect, fixes redirects.
> Fix no-body fatal errors

- package.json
- src/app-mixin.jsx
- src/views/pages/BasePage.jsx
Specifically for: https://github.com/reddit/snoode/pull/56
This helps renders on error pages for API timeouts, which won't have data.
> Fix no-data error page rendering

- assets/js/client.es6.js
- src/routes.jsx
- src/views/components/TopNav.jsx
- src/views/pages/submit.jsx
this was on my message-compose branch. Might as well get it out
now follows the same urls as .com, accepts query parameters to pre populate fields.
> Submit: make url match reddit.com, some refactoring

- index.js
- src/server/index.jsx
> Add process pids to startup log

- src/routes.jsx
Health and other routes were loading subreddit and user data, which is
unnecessary, and just slows everything down.
> Refactor loading sub/userdata

- index.js
- package.json
- src/app-mixin.jsx
- src/config.es6.js
- src/server/console.es6.js
- src/server/index.jsx
:eyeglasses: @curioussavage, @umbrae 
This adds:
* snoode api request logging (via https://git.io/vlxC1)
* active open requests logging stub (so we can track this in statsd later)
* a developer console, enableable with the `--console` flag (`node index.js --console`)
If the console is up, it will write logs to `reddit-mobile.log` in your project directory, clearing it out each time you start up the console.
http://gfycat.com/NegligibleAdorableBat
> Server console

- src/views/pages/BasePage.jsx
Fix infinite loop caused by an `undefined` dataCache value.
> Fix infinite loop

- src/app-mixin.jsx
:eyeglasses: @umbrae and/or @spladug
> Filter out 429s and timeouts from logs

- README.md
- hooks/pre-commit
- hooks/pre-push
- src/views/components/Modal.jsx
- test/helpers/renderWithProps.jsx
Next step, to add a git pre-commit hook to auto-run tests on commit.
> Fixes test warnings, and adds pre-commit and pre-push hooks

- src/views/components/Listing.jsx
- src/views/components/ListingContent.jsx
> Ad img refactor

- src/views/pages/subredditAbout.jsx
It appears that the div with html needs to be self closing.
weird...
> Fix subredditAboutPage

- src/views/pages/register.jsx
https://reddit.atlassian.net/browse/MOBILEWEB-270
Updates privacy test to match desktop
@ajacksified
> Update privacy text to match desktop

- assets/js/client.es6.js
- src/EUCountries.es6.js
- src/constants.es6.js
- src/routes.jsx
- src/views/components/InfoBar.jsx
changes:
* view count for cookie starts at one like desktop.
* moved code to set cookie into infobar so it runs before modify context. plus for simplicity as its not used by any other components.
* added a key to bodylayout 
* use lodash to find/filter messages. (my function had a bug :( )
up on staging now
> Eu galletas

- assets/js/client.es6.js
- assets/less/components/TopNav.less
- src/constants.es6.js
- src/views/components/Dropdown.jsx
https://reddit.atlassian.net/browse/MOBILEWEB-137
Hides Dropdowns when other elements on the page are clicked
> Hide Dropdowns on clicks outside of dropdowns

- src/views/components/ListingContainer.jsx
- src/views/components/ListingList.jsx
- src/views/components/ListingPaginationButtons.jsx
- src/views/pages/index.jsx
- src/views/pages/search.jsx
- src/views/pages/userActivity.jsx
- src/views/pages/userSaved.jsx
- test/helpers/components.es6.js
- test/views/pages/Index.jsx
- test/views/pages/userSaved.jsx
https://reddit.atlassian.net/browse/MOBILEWEB-329
Creates a new component `ListingContainer` to manage the compact state of `ListingList`. Passes the initial compact state everywhere so search pages, user saved, and user submitted posts respect the preference.
https://reddit.atlassian.net/browse/MOBILEWEB-315
Creates a new component `ListingPaginationButtons` to manage the next|prev buttons on listings. Fixes generating pagination buttons for the search page so they appear.
> Respect compact preference everywhere. Fix search pagination

- src/views/pages/BasePage.jsx
> Do not fire pixel server side

- assets/js/trackingEvents.es6.js
- package.json
- src/config.es6.js
- src/views/pages/BasePage.jsx
- src/views/pages/listing.jsx
:eyeglasses: @curioussavage or @schwers
> Screenview

- src/views/components/CaptchaBox.jsx
Broke here: https://github.com/reddit/reddit-mobile/commit/3839c16ecaa55045a664f82b4f831317918c0604#diff-fb32cc3aa413b36bc8fcdb343c72d0edR85
> Fix captchas

- README.md
Also fixes a typo
:eyeglasses: @ajacksified or @schwers
> README: update for new node/npm versions.

- src/views/components/ListingContainer.jsx
- src/views/components/ListingPaginationButtons.jsx
- src/views/pages/index.jsx
- src/views/pages/search.jsx
- src/views/pages/userActivity.jsx
- src/views/pages/userSaved.jsx
:eyeglasses: @curioussavage or @schwers 
https://reddit.atlassian.net/browse/MOBILEWEB-342
Adds paging for user profile activity and user saved/hidden pages. Also fixes a bug with index paging.
> User activity paging

- src/server/index.jsx
Instead of trying to refresh a token when a tokenExpires exists but a
token doesn't, nuke the invalid cookies.
:eyeglasses: @schwers @umbrae
> Ignore empty token cookies

- assets/less/base.less
- assets/less/components/wikiPage.less
- src/redirects.jsx
- src/routes.jsx
- src/views/components/SideNav.jsx
- src/views/components/TopNav.jsx
- src/views/pages/wikiPage.jsx
Also used to display privacy policy
:eyeglasses: @ajacksified @schwers
> Add WikiPage

- assets/js/client.es6.js
- src/app-mixin.jsx
:eyeglasses: @ajacksified (Can you advise me how to test this with hivemind / how does this affect your client-side logging?)
> Update client app's env to be client

- assets/js/client.es6.js
- src/constants.es6.js
- src/views/layouts/DefaultLayout.jsx
- src/views/pages/BasePage.jsx
> Set meta key color based on subreddit key color

- assets/less/components/Submit.less
This was preventing search from scrolling while posting.
Also increases height of the bottom div to fix scrollbar
> remove overflow css property on submit page wrapper.

- src/server/index.jsx
> Default user-agent to empty-string

- assets/js/client.es6.js
- src/app-mixin.jsx
:eyeglasses: @ajacksified https://github.com/schwers/reddit-mobile/blob/03fd02fc939c3fae0dca97b273425fc4cbcf49e1/src/app-mixin.jsx#L29 was the line I had to change
> Update client env to be client, with fix for undefined ctx

- src/views/components/GoogleCarouselMetadata.jsx
- src/views/pages/listing.jsx
:eyeglasses: @curioussavage and also @xilvar
> Patch up google carousel metadata

- src/views/components/GoogleCarouselMetadata.jsx
- src/views/pages/listing.jsx
And a little bit of cleanup.
:eyeglasses: @schwers or @curioussavage
> Pull isGoogleCrawler from ctx, not props

- assets/js/trackingEvents.es6.js
This updates trackingEvents. Each commit should have the related tickets in each commit. I combined ones that were related.
:eyeglasses: @ajacksified @drunken-economist
> Tracker updates

- assets/less/components/TextSubNav.less
- assets/less/components/wikiPage.less
- assets/less/mixins.less
- src/routes.jsx
- src/views/components/MessageNav.jsx
- src/views/components/TextSubNav.jsx
- src/views/components/TopNav.jsx
- src/views/pages/subredditAbout.jsx
- src/views/pages/wikiPage.jsx
:eyeglasses: @ajacksified @schwers @nramadas 
https://reddit.atlassian.net/browse/MOBILEWEB-365
just cleaning up the wikiPage, made revisions look better. also revision link takes you to revisions for the current page only as long as you are not on the pages route.
depends on: https://github.com/reddit/snoode/pull/71
> Restyle wiki

- assets/less/components/CommunityHeader.less
https://reddit.atlassian.net/browse/MOBILEWEB-374
> Make community header banner render at 10:3

- src/app-mixin.jsx
- src/lib/errorLog.es6.js
> Tack on client-side useragent for simpleUA

- src/routes.jsx
- src/server/index.jsx
- src/views/pages/listing.jsx
Cloudflare returns cached data with no Google metadata often. So always
render it.
:eyeglasses: @xilvar and @umbrae and maybe @schwers
> Server should always send google metadata

- src/lib/errorLog.es6.js
> Fix googlebot's mobile js crawler classification

- package.json
https://github.com/reddit/event-tracker/commits/master
> upgrade event tracker

- assets/js/client.es6.js
- assets/js/frames.es6.js
- assets/js/gtm.es6.js
- assets/js/trackingEvents.es6.js
- hooks/pre-commit
- package.json
:eyeglasses: @schwers or @ajacksified or @nramadas 
this will only lint staged js files on pre commit
> pre-commit: lint only changed js files

- src/views/pages/listing.jsx
Fixes the issue with permalink's being undefined in the dropdowns
> Fix permalink's not working in comments

- src/views/components/ListingContent.jsx
I've noticed playing gif's doesn't work as expected. When you tap a gif we change the preview image to an embedly embed, but that doesn't really autoplay the gif so you have to then tap a second time. This is even worse when it's a gfycat gif. This path uses the current html5 video rendering code, and uses it when you tap a gif, with some modifications so autoplay works on iOS. 
As part of this I looked into why preview images are blurry and why iOS gifs don't play inline. Preview images are still blurry in some cases (the ones we make for gfycat tend to be lower res) and could be fixed by always using the html5 video element which fetches the first frame for display.. In practice I'm not sure that's the right approach; some _very_ brief research makes it sound like setting …
> Play gifs after one-tap in most cases. Support gfycat.

- src/routes.jsx
- src/views/pages/index.jsx
:eyeglasses: @schwers or @curioussavage
> Server fixes

- src/views/components/ListingContent.jsx
with this removed the videos only show previews
> listingContent: add back check for video playing status

- src/server/routes.es6.js
:eyeglasses: @ajacksified or @nramadas or @schwers 
let me know if I am forgetting one.
> Robots.txt: add messages and submit routes

- src/lib/gifToHTML5Sources.es6.js
- src/views/components/ListingContent.jsx
- test/lib/gifToHTML5Sources.es6.js
My gif autoplay patch broke video playing. But I didn't realize that or that it was patched. This attempts to make both of those coexist and fixes imgur.gifv's
> Fix clash of gifs autoplaying breaking video embeds

- src/lib/gifToHTML5Sources.es6.js
- src/views/components/ListingContent.jsx
- test/lib/gifToHTML5Sources.es6.js
[example of a gif that plays correctly now because of posing like a gallery link](https://m.reddit.com/r/HighQualityGifs/comments/45esfv/what_the_hobbit_needed_was_more_fx/)
> Fix galleries, and imgur that look like galleries or jpg

- src/server/oauth.es6.js
:eyeglasses: @KeyserSosa and @schwers 
This will allow r2 to perform different checks for internal, trusted clients, such as allowing reddit-mobile to implement its own captcha.
> Add secret oauth to auth header for registration

- src/views/components/Ad.jsx
- src/views/components/ListingList.jsx
Related changes in the ads plugin:
https://github.com/reddit/reddit-plugin-adzerk/commit/f435cf06524cfa73763b069f9dc6e18a4fd490f6
https://github.com/reddit/reddit-plugin-adzerk/commit/5e7bc4ce6ca8136f1b9b021f3b0c2295abd600da
:eyeglasses: @ajacksified Let me know if you want someone else on the team to look at this.
> Ads updates

- src/views/components/listings/PostAndCommentList.jsx
Did this for `ListingList`, but missed this component.
> PostAndCommentList.jsx: Pass `site` to `<Ad />` instead of `srnames`.

- src/views/components/Ad.jsx
bug introduced here: https://github.com/reddit/reddit-mobile/commit/a8e00f2b66f4e25082f0c57626b1f7970eb198b6#diff-2df9f64054b7cb0e816eade2a7a72605R90
> Fix ads response check

- src/views/components/listings/PostFooter.jsx
- src/views/components/listings/PostHeader.jsx
:eyeglasses: @schwers Sorry for picking on you, let me know if you want me to ask some other people to review.
> Do not render comment link if comments are disabled

- assets/js/clientEvents.es6.js
> Don't capture ctrl/cmd key clicks

- src/lib/makeRequest.es6.js
- src/routes.jsx
Fixes:
* goto r/<Community> finder in the community menu
* r/random
> Make superer-agent a superhero

- assets/less/components/listings/PostContent.less
- assets/less/components/listings/PostFooter.less
- assets/less/components/listings/PostHeader.less
- src/views/components/UserOverlayMenu.jsx
- src/views/components/listings/Post.jsx
- src/views/components/listings/PostAndCommentList.jsx
- src/views/components/listings/PostContent.jsx
- src/views/components/listings/PostHeader.jsx
- src/views/components/listings/postUtils.es6.js
* Depends on some minor nit patches in [524](https://github.com/reddit/reddit-mobile/pull/524/files)
* Pending a small question re: domain vs TLD and prefixless domains for link attribution
> Media preview and link behavior changes for post redesign

- src/views/components/listings/postUtils.es6.js
:eyeglasses: @nramadas or @curioussavage
> Fix replace of undefined error

- assets/less/animations/importAll.less
- assets/less/animations/voteBounce.less
- assets/less/base.less
- assets/less/components/comment/CommentTools.less
- assets/less/components/listings/PostFooter.less
- assets/less/variables.less
- src/views/components/comment/CommentTools.jsx
- src/views/components/listings/PostFooter.jsx
This updates comment's voteing arrows to:
* have the same hit areas as the listings arrows. Part of this change is making the score an upvote target.
All vote arrows now use the bounce animation, similar to the app betas.
> Update comment vote arrows. Add vote bounce animation.

- assets/js/trackingEvents.es6.js
> Don't instantiate Tracker without config

- assets/js/trackingEvents.es6.js
- src/views/components/LinkTools.jsx
- src/views/components/comment/Comment.jsx
- src/views/pages/listing.jsx
- src/views/pages/submit.jsx
Just two more events here.
I also did default new posts to type of text since if the user doesn't type anything down there it says its a link post. This was checked on submission but I didn't like that the ui didn't reflect the state accurately before submission.
> Events galore

- src/views/components/LinkTools.jsx
- src/views/pages/listing.jsx
A reference to user.id was throwing an error since user was not defined
> listing: fix undefined error

- src/views/components/CommunitySearchRow.jsx
Finding a subreddit by name is annoying, particularly with iOS's aggressive autocorrect
> Turn-off autocomplete and correct for subreddit search

- src/views/layouts/DefaultLayout.jsx
> Turn GA sample rate down from 50% to 10%

- assets/less/components/Submit.less
- assets/less/components/wikiPage.less
- src/views/pages/submit.jsx
:eyeglasses: @nramadas 
just some quick fixes for night mode, plus 2 little fixes for submit
> nightmode fixes plus fix subreddit select in submit

- assets/less/base.less
- assets/less/components/NSFWFlair.less
- assets/less/components/listings/PostHeader.less
- src/views/components/CommunityOverlayMenu.jsx
- src/views/components/NSFWFlair.jsx
- src/views/components/communities/CommunityRow.jsx
* Makes NSFW flair on post headers smaller from design feedback
* Adds a NSFW flair to subreddits listed in subscriptions and search. This is useful if you don't know the subreddit is NSFW and it shows up in search results or just as a reminder when looking through your subreddit list
> Adjust NSFW treatment for posts. Add it to subreddit lists.

- assets/js/clientEvents.es6.js
:eyeglasses: @schwers and @drunken-economist 
@drunken-economist - made this change before we discussed moving mweb to utm, so wanted to get your input before this goes in.
> Change ?ref on "view desktop" to mweb_navbar

- assets/js/client.es6.js
- assets/less/base.less
- assets/less/components/DefaultLayout.less
- assets/less/components/InfoBar.less
- assets/less/components/SmartBanner.less
- assets/less/variables.less
- src/constants.es6.js
- src/featureflags.es6.js
- src/lib/initBanner.es6.js
- src/lib/smartBannerState.es6.js
- src/views/components/SmartBanner.jsx
- src/views/components/listings/PostAndCommentList.jsx
- src/views/layouts/DefaultLayout.jsx
- src/views/pages/BasePage.jsx
> Create a custom banner

- assets/js/appMethods.es6.js
- assets/js/client.es6.js
- src/config.es6.js
- src/server/index.jsx
> Add 'geotagging' to the smartbanner

- assets/less/components/SmartBanner.less
- src/featureflags.es6.js
- src/lib/smartBannerState.es6.js
- src/views/components/SmartBanner.jsx
> Turn on the smart banner for everyone

- src/constants.es6.js
> Change the measurement urls for the smart banner

- src/server/routes.es6.js
remove routes that other applications will
never need to know about from routes
> routes: remove some endpoints

- src/redirects.jsx
The non subreddit url had 'hot' hardcoded. also eliminated the forEach
> redirects: fix sorting redirect for listings.

- src/views/pages/submit.jsx
> Submit: fix subreddit being sent in submit

- src/views/pages/submit.jsx
:eyeglasses: @ajacksified  
uh, oops heres there real fix for the request
> Submit: real fix for subreddit prop in request

- assets/js/trackingEvents.es6.js
- src/views/components/SubredditSelectionButton.jsx
- src/views/pages/submit.jsx
> Submit repairs

- src/views/pages/BasePage.jsx
> remove unneeded call to forceRender

- assets/js/trackingEvents.es6.js
- src/views/layouts/DefaultLayout.jsx
We need this to send full urls to comscore.
👓 @ajacksified 
see ref: https://github.com/reddit/reddit-mobile/pull/446
> GTM: Add `pathname` data layer variable

- src/routes.jsx
> Set page title and meta-description on comment pages

- assets/js/clientEvents.es6.js
> Fix typo - s/reconected/reconnected/

- package.json
- src/app/components/AppTopNav/index.jsx
- src/app/pages/AppMain.jsx
> Platform 0.1.0

- package.json
- src/Client.js
- src/Server.js
- src/app/pages/Comments.jsx
- src/app/router/handlers/CommentsPage.js
- src/app/router/handlers/PostsFromSubreddit.js
👓 @schwers 
Depends on https://github.com/reddit/node-platform/pull/1
> Enable shell-rendering

- package.json
- src/app/actions/communityGoto.js
- src/app/actions/subreddits.js
- src/app/models/SubredditRequests.js
- src/app/reducers/index.js
- src/app/reducers/subredditRequests.js
- src/app/router/handlers/CommunityGotoAction.js
Depends on https://github.com/reddit/node-api-client/pull/112
> Fix goto subreddit bar

- package.json
- src/app/actions/apiResponse.js
- src/app/actions/overlayMenu.js
- src/app/actions/subreddits.js
- src/app/components/CommunityHeader/index.jsx
- src/app/components/CommunityHeader/styles.less
- src/app/models/SubscribedSubreddits.js
- src/app/pages/PostsFromSubreddit.jsx
- src/app/reducers/apiResponse.js
- src/app/reducers/index.js
- src/app/reducers/subscribedSubreddits.js
- src/app/router/handlers/PostsFromSubreddit.js
- src/app/router/handlers/ToggleSubredditSubscription.js
- src/app/router/index.js
- src/lib/isFakeSubreddit.js
depends on https://github.com/reddit/node-api-client/pull/114/files
> Subreddit headers

- src/app/actions/comment.js
- src/app/actions/vote.js
- src/app/components/Comment/CommentReplyForm/index.jsx
- src/app/components/Comment/CommentReplyForm/styles.less
- src/app/components/Comment/CommentTools/index.jsx
- src/app/components/Comment/CommentTools/styles.less
- src/app/components/Comment/index.jsx
- src/app/reducers/index.js
- src/app/reducers/replying.js
- src/app/router/handlers/CommentsPage.js
- src/app/router/handlers/Vote.js
- src/app/router/index.js
- src/app/styles.less
UI in place; API stubbed.
👓 @schwers
> comment replies

- package.json
- src/app/actions/apiResponse.js
- src/app/actions/comment.js
- src/app/actions/vote.js
- src/app/components/Comment/CommentReplyForm/styles.less
- src/app/components/CommentsPage/CommentsPageTools/index.jsx
- src/app/components/CommentsPage/CommentsPageTools/styles.less
- src/app/pages/Comments.jsx
- src/app/reducers/apiResponse.js
- src/app/reducers/commentsPages.js
- src/app/router/handlers/CommentsPage.js
👓 @schwers 
depends on https://github.com/reddit/node-api-client/pull/115
> Implement voting and replying in API

- src/server/routes.es6.js
Also a quick update to the robots.txt -- blacklisting
another crawler to match what's on www.reddit.com.
:eyeglasses: @schwers @prashtx
> Add a static json endpoint for supporting deep linking on iOS

- src/server/routes.es6.js
YAY ME!
:eyeglasses: @schwers @prashtx
> Fix a key typo in the apple-app-site-association

- .gitignore
- package.json
> add test watcher script to package.json

- .gitmodules
> Use reddit/art-gallery

- src/constants.es6.js
- src/featureflags.es6.js
- src/views/components/TopNav.jsx
- test/src/featureflags.es6.js
> Update snoo logo

- src/views/components/LinkTools.jsx
- src/views/components/comment/Comment.jsx
- src/views/components/comment/CommentTools.jsx
- src/views/components/listings/Post.jsx
- src/views/components/listings/PostFooter.jsx
- src/views/pages/listing.jsx
This works by hiding or getting rid of click events
in specific places.
👓  @schwers @nramadas 
Using https://m.reddit.com/r/IAmA/comments/1vzh42/donald_faison_ama_all_welcome/ to test... before:
After:
> Support for archived posts.

- package.json
- src/Client.js
- src/Server.js
- src/app/actions/posts.js
- src/app/actions/preferences.js
- src/app/actions/user.js
- src/app/components/NSFWInterstitial/index.jsx
- src/app/components/NSFWInterstitial/styles.less
- src/app/components/Post/index.jsx
- src/app/components/Post/postUtils.js
- src/app/components/PostsList/index.jsx
- src/app/models/User.js
- src/app/pages/PostsFromSubreddit.jsx
- src/app/reducers/index.js
- src/app/reducers/preferences.js
- src/app/reducers/preferences.test.js
- src/app/reducers/preferencesRequest.js
- src/app/reducers/preferencesRequest.test.js
- src/app/reducers/unblurredPosts.js
- src/app/reducers/unblurredPosts.test.js
- src/app/reducers/user.js
- src/app/reducers/user.test.js
- src/app/router/handlers/SetOver18.js
- src/app/router/handlers/handlerCommon.js
- src/app/router/index.js
- src/app/side-effect-components/CookieSync.js
- src/server/initialState/dispatchInitialOver18.js
Depends on https://github.com/reddit/node-api-client/pull/132 (git path hardcoded in package.json for testing purposes only)
NSFW subreddits will now have a NSFW interstitial if we haven't confirmed the user is over 18. If the user is logged in that confirmation will come from the preferences object. We weren't fetching it before but have to use the endpoint anyway to update that preference, so now we're fetching it as well. This sets up for using default comment sort and etc.
Posts in non-nsfw subreddits will now have the proper NSFW label and tap/click'ing them will toggle the blur.
👓 @nramadas @phil303
> Adds NSFW Interstitial and post blurring support

- src/Client.js
- src/app/actions/commentsPage.js
- src/app/components/RelevantContent/index.jsx
- src/app/components/RelevantContent/styles.less
- src/app/constants.js
- src/app/featureFlags.js
- src/app/pages/Comments.jsx
- src/app/reducers/index.js
- src/app/reducers/visitedPosts.js
- src/app/reducers/visitedPosts.test.js
- src/app/router/handlers/CommentsPage.js
- src/app/selectors/userAccount.js
- src/app/side-effect-components/LocalStorageSync.js
Add support for a variant of the next-content experiment. We will likely
tweak the variant and add others, but it's useful to have a basic
experiment present, so we can properly hook up the feature flag and
event code.
> Relevancy experiment initial code

- src/app/router/handlers/ToggleSubredditSubscription.js
> Fix subscription handler from refactor

- src/featureflags.es6.js
We're temporarily restricting this test to one subreddit, so that we can increase the bucket sizes and test that subreddit's traffic specifically.
> Restrict nextcontent_mweb experiment to r/pokemongo

- package.json
- src/app/components/Comment/index.jsx
- src/app/components/Messages/Comment.jsx
- src/app/components/Messages/Message.jsx
- src/app/components/Post/PostContent/index.jsx
- src/app/components/RedditLinkHijacker/index.js
- src/app/components/SubredditAbout/index.js
- src/app/components/Wiki/index.js
👓 @phil303 
Depends on https://github.com/reddit/node-platform/pull/14 (hardcoded for testing)
> Use LinkHijacker to allow ugc links to drive app navigation.

- CONFIG.md
- assets/js/trackingEvents.es6.js
- src/config.es6.js
- src/lib/dom.es6.js
- src/lib/makeRequest.es6.js
- src/views/components/Ad.jsx
- src/views/components/listings/PostAndCommentList.jsx
- src/views/layouts/BodyLayout.jsx
👓 @schwers 
ticket: https://reddit.atlassian.net/browse/ADS-591
adblock disabled:
blocking endpoint:
blocking element:
> Adblock instrumentation

- src/views/components/listings/Post.jsx
- src/views/components/listings/PostContent.jsx
> Fix s/porpTypes/propTypes/ and related issues

- package.json
- src/app/components/PostsList/index.jsx
> Convert undefined into a bool, for proptypes, in PostsList

- src/app/components/Login/Input.jsx
- src/app/components/Login/Input.less
- src/app/components/Login/SquareButton.jsx
- src/app/components/Login/SquareButton.less
- src/app/components/Login/index.jsx
- src/app/components/Login/styles.less
This makes the login page look more along the
lines of the 1X login page, but a bare bones
version of it. The subcomponents are brought over
from there, and more will come in subsequent
updates.
:eyeglasses: @schwers @phil303 
Feel free to rip at this -- again, this part is just what
was there in 1X. Maybe we don't want these subcomponents 
where I put them.  Maybe we want them cleaned up more.
Just doing things in steps to make for smaller things to review.
> Login view cosmetic update

- package.json
- src/app/actions/posting.js
- src/app/actions/subredditAutocomplete.js
- src/app/components/AppOverlayMenu/index.jsx
- src/app/components/CaptchaBox/index.jsx
- src/app/components/CaptchaBox/styles.less
- src/app/components/DropdownCover/index.jsx
- src/app/components/Modal/styles.less
- src/app/components/PostSubmitCommunityModal/index.js
- src/app/components/PostSubmitCommunityModal/styles.less
- src/app/components/PostSubmitModal/index.jsx
- src/app/components/PostSubmitModal/styles.less
- src/app/components/PostSubmitOverlay/index.jsx
- src/app/components/PostSubmitOverlay/styles.less
- src/app/reducers/autocompleteSubreddits.test.js
- src/app/reducers/posting.js
- src/app/reducers/posting.test.js
- src/app/reducers/recentSubreddits.js
- src/app/reducers/recentSubreddits.test.js
- src/app/router/handlers/PostSubmit.js
> Post submit - backend/tests/captcha box

- blueprints.config.js
- package.json
- src/Client.js
- src/Server.js
- src/server/templates/main.jsx
Depends on improvements to @r/build from https://github.com/reddit/node-build/pull/19
> Productionnificationize

- package.json
We should be able to verify this with the CI status on this PR.
> Bump build to fix tests

- package.json
- src/server/meta/index.js
> Add a /health endpoint

- src/app/actions/scrollPosition.js
- src/app/index.jsx
- src/app/reducers/index.js
- src/app/reducers/scrollPositions.js
- src/app/reducers/scrollPositions.test.js
- src/app/side-effect-components/CookieSync.js
- src/app/side-effect-components/DomModifier.js
- src/app/side-effect-components/LocalStorageSync.js
- src/app/side-effect-components/ScrollPositionSync.js
- src/app/side-effect-components/SessionRefresher.jsx
> Add a side-efect component for ScrollPosition sync

- src/routes.jsx
- src/views/layouts/DefaultLayout.jsx
Fix an issue preventing the existing canonical-url implementation from kicking in.
Set actual canonical URLs for paths where the mobile-web and desktop URLs don't match.
> Expose canonical URLs

- assets/js/client.es6.js
- src/app-mixin.jsx
I tested this locally by simulating an timeout in loading `/hot.json` from the frontpage. You can try this by linking `node-api-client` and then in `node-api-client/old-src/endpoints/v1.es6.js` on line 160 in `returnGETPromise` [[src]](https://github.com/reddit/node-api-client/blob/master/old-src/endpoints/v1.es6.js#L160) add the following:
```javascript
if (options.uri === 'https://www.reddit.com/hot.json') {
err = {
status: 503,
message: 'fake error for testing retrying',
};
}
```
This simulates a 503 of the listing endpoint hitting `hot.json` Note: this assumes you're logged out, you can edit the `options.uri` comparison
👓  @nramadas
> Prevent client from re-trying failed server-side requests

- assets/js/clientEvents.es6.js
> Up the desktop redirect expiration to 365 days

- src/views/components/Ad.jsx
> Ads: Send placement name to request endpoint

- src/app/components/Comment/CommentHeader/index.jsx
- src/app/components/Comment/CommentHeader/styles.less
- src/app/components/Comment/index.jsx
- src/app/components/Comment/styles.less
- src/app/components/Dropdown/styles.less
- src/app/components/Loading/styles.less
- src/app/components/PaginationButtons/styles.less
- src/app/components/Post/PostFooter/index.jsx
- src/app/components/Post/PostHeader/index.jsx
- src/app/components/Post/PostHeader/styles.less
- src/app/components/Post/styles.less
- src/app/components/PostAndCommentList/index.jsx
- src/app/components/PostsList/index.jsx
- src/app/components/SubNav/styles.less
- src/app/less/icon-font.less
- src/app/less/normalizers/redditReset.less
- src/app/pages/Comments.jsx
- src/app/router/handlers/Vote.js
Depends on fixes to voting mixing in api-client, see https://github.com/reddit/node-api-client/pull/142
> 2 x bug cleanup

- package.json
- src/app/components/Comment/index.jsx
- src/app/components/Post/PostHeader/index.jsx
> Fix flair -- they weren't using the aliased names

- package.json
- src/app/components/Comment/index.jsx
For the highlighting, most of the code is already there, just needed to
hook up the commentId from the state to know which one.
Also bumping @r/build to 0.9.4 and @r/api-client to 3.20.4  …
- New @r/build fixes SourceMaps!
- New @r/api-client fixes permalink fetching and adds
raw_json=1 to the Posts requests, which was breaking
a number of things on the content side.
👓  @schwers @phil303
> Permalink highlighting

- src/app/components/GoogleCarouselMetadata/index.jsx
- src/app/components/GoogleCarouselMetadata/index.test.js
- src/app/pages/Comments.jsx
- src/app/selectors/crawlerRequestSelector.js
- src/lib/safeStringify.js
👓  @uzi or @nramadas 
For verification of channels related stuff:
👓  @prashtx or @wting 
I made some changes related to the structured data fields, see https://reddit.atlassian.net/browse/CHAN-124 for explanation
> Add GoogleCarouselMetadata to comments 

- src/config.es6.js
- src/server/oauth.es6.js
- src/views/components/ReCaptcha.jsx
- src/views/layouts/DefaultLayout.jsx
- src/views/pages/login.jsx
Add a new ReCaptcha component that follows the API at
https://developers.google.com/recaptcha/docs/display
and make use of it in account registration.
> Add ReCaptcha to account registration

- src/views/pages/login.jsx
This is to fix 1X ... somehow I missed this ... I swear I tested it!  (Or thought I did...)
> Fix the ReCaptcha callback parameter for registration

- src/app/components/Comment/CommentTools/index.jsx
- src/app/components/Comment/index.jsx
- src/app/components/CommentsPage/CommentsPageTools/index.jsx
- src/app/components/CommentsPage/CommentsPageTools/styles.less
- src/app/components/Post/PostFooter/index.jsx
- src/app/components/Post/index.jsx
- src/app/components/Vote/index.jsx
- src/app/less/themes/dayMode.less
- src/app/less/themes/nightMode.less
- src/app/less/variables.less
- src/app/pages/Comments.jsx
- src/app/styles.less
I'm actually having trouble messing around with themeify css. Could someone teach me? 
Otherwise:
**locked**
**single comment**
**archived**
**night mode**
👓  @uzi @phil303
> Add warning alert for archived, locked, and commentID posts

- src/app/components/Comment/CommentDropdown/index.jsx
A quick one, :eyeglasses: @schwers
> Comment out the "edit" option in the dropdown

- package.json
- src/app/components/LoginRegistrationForm/styles.less
- src/app/components/ReCaptcha/index.jsx
- src/app/components/ReCaptcha/styles.less
- src/app/components/Register/index.jsx
- src/app/models/Register.js
- src/app/router/handlers/Register.js
- src/config.js
- src/server/session/registerproxy.js
A few things to fix still, primarily around the loading of the code from Google, and a few other things to chat about before the eyeglasses come out... but overall it seems to work.
> Add ReCaptcha to the register page

- src/views/components/ReCaptcha.jsx
- src/views/layouts/DefaultLayout.jsx
Bring the ReCaptcha script loading into the component, protected by a promise.
> Load Recaptcha in the component, guarded by a promise

- package.json
- src/app/actions/comment.js
- src/app/actions/commentsPage.js
- src/app/components/Comment/index.jsx
- src/app/components/Comment/styles.less
- src/app/components/CommentsList/index.jsx
- src/app/components/CommentsList/styles.less
- src/app/pages/Comments.jsx
- src/app/reducers/comments.js
- src/app/reducers/comments.test.js
- src/app/reducers/index.js
- src/app/reducers/moreCommentsRequests.js
- src/app/reducers/moreCommentsRequests.test.js
- src/app/reduxMiddleware/errorLogger.js
It's open season baby! Feel free to review this in a more granular way - some of it will be subject to change after our live review.
> More comments

- package.json
- src/app/reduxMiddleware/errorLogger.js
- src/lib/errorLog.js
This fixes things for logging 2X Errors and APIErrors to Hivemind.  It's dependent on https://github.com/reddit/hivemind/pull/25 also being rolled out ahead of it.
> Error logging fixes

- .ackrc
Ack is a useful find/grep sort of utility. It can
help folks understand out codebase quicker.  This
hides generated files from searches to make things
friendlier.
> Add .ackrc

- src/views/pages/listing.jsx
> React doesn't like P tags inside P tags -- get rid of that.

- src/server/oauth.es6.js
- src/views/components/listings/mediaUtils.es6.js
> Fix a pair of 1X errors

- src/server/oauth.es6.js
> Check that we have an actual modhash

- assets/js/appMethods.es6.js
- assets/js/client.es6.js
- assets/js/clientEvents.es6.js
- assets/js/clientLib.es6.js
- package.json
- src/app-mixin.jsx
- src/config.es6.js
- src/featureflags.es6.js
- src/routes.jsx
- src/server/config.es6.js
- src/server/index.jsx
- src/server/oauth.es6.js
- src/server/session.es6.js
- src/views/components/Ad.jsx
- src/views/pages/login.jsx
- test/src/featureflags.es6.js
> Convert 1X cookies to use 2X format. Move to root domain.

- src/lib/mobilify.es6.js
👓 @schwers @phil303 @nramadas @umbrae
> Fix a small bug in the mobilify helper function

- src/lib/mobilify.js
> mobilify updates for the 2X branch

- .dockerignore
- Dockerfile.dev
- Dockerfile.varnish
- default.vcl
- docker-compose.yml
Same as #738 (cherry-picked it over). Verified working on my machine.
:eyeglasses: @gtaylor
> Put Varnish in front of Node via docker-compose.

- src/app/router/handlers/handlerCommon.js
- src/server/initialState/permanentCookieOptions.js
I have this as two separate commits with reasoning in their messages. But essentially this fixes the login issue and the cookie issue on staging.
👓  @nramadas || @uzi
> 2 x auth stuff

- .drone.yml
- Dockerfile.dev
- Dockerfile.staging
Similar to https://github.com/reddit/modmail/pull/44.
:eyeglasses: @spladug @ckwang8128
> Pull base images from Quay instead of Docker Hub.

- src/lib/visitedPosts.es6.js
We were writing a comma separated string in 1X and
it's a JSON array in 2X. This will store things as
an array and convert from old to new.
👓 @schwers @phil303 @nramadas
> Store and convert localStorage.visitedPosts in JSON

- src/Client.js
If we see the old style visitedPosts, we're able to
read them. Also added a bit of code to handle the
initial state a bit better.
👓 @schwers @phil303 @nramadas
> Support old style localStorage.visitedPosts

- src/server/routes.es6.js
> Whitelist action names

- src/lib/eventUtils.js
Sometimes the subreddit fails to load, either due to the sub
being private, quarantined, or just a general API failure.
This fix prevents us from throwing an error while trying to build
screenview data when the subreddit data didn't load.
👓  @phil303 || @uzi 
This should be the source of the `cannot read property 'name' of undefined` errors in the tap.
e.g. log:
```js
{
"column": "2661",
"env": "CLIENT",
"isAPIFailure": false,
"line": "8",
"message": "Error: Cannot read property 'name' of undefined",
"reduxInfo": "Redux Action Stack: \"PLATFORM__SET_STATUS\", \"FAILED_PREFERENCES\", \"FAILED_SUBREDDIT\", \"RECEIVED_COMMENTS_PAGE\",{\"type\":\"FETCHING_SUBREDDIT\",\"name\":\"askscience\"}, \"VISITED_COMMENTS_PAGE\", \"PENDING_PREFERENCES\",{\"type\":\"FETCHING_COMMENTS_PAGE\",\"commentsPage …
```
> Check for subreddit before building it's event data.

- src/app/components/Post/PostContent/index.jsx
- src/lib/gifToHTML5Sources.js
- test/lib/gifToHTML5Sources.test.js
Fixing:
* An exception when a certain ad with no preview image is loaded
* An exception with gfycat videos that have additional hash arguments
* A small cosmetic fix
* A typo
👓 @schwers @phil303 @nramadas
> Fix a pair of exceptions and some other stuff

- src/server/meta/index.js
Detect the cases where timings aren't sent or
we're missing an actionName.
👓  @schwers
> A little more timings endpoint hardening.

- .drone.yml
> Move the drone messages from #frontend-platform to #mobile-web

- src/app/components/Messages/Comment.jsx
- src/app/components/Messages/Comment.less
- src/app/components/Messages/Message.jsx
- src/app/components/Messages/Message.less
For both comment and message components, make more
things clickable and style them appropriately.
A small piece of the messaging work, but trying to break things
up into smaller chunks for easier review.
> Some display and linking updates to message components

- src/app/constants.js
- src/app/router/handlers/Messages.js
- src/app/router/handlers/PostSubmit.js
- src/app/router/handlers/Vote.js
Since this may change in the future, making it a constant will make it
easier to do updates.
> make the logged out redirect location a constant

- assets/svg/megaphone.svg
- src/app/components/Post/PostDropdown/index.jsx
- src/app/components/Post/PostHeader/index.jsx
- src/app/components/Post/PostHeader/styles.less
- src/app/components/Post/index.jsx
👓 @dwick
Behavior:
Clicking on PostHeader leads to promotedUrl
Clicking on content leads to cleanUrl (to the click tracker
Clicking on comments leads to the original post
> Add promoted user post ad type

- package.json
- src/app/actions/mail.js
- src/app/components/DirectMessage/Composition.jsx
- src/app/components/DirectMessage/Composition.less
- src/app/components/DirectMessage/Header.jsx
- src/app/components/DirectMessage/index.jsx
- src/app/components/MessageThread/index.jsx
- src/app/components/MessageThread/styles.less
- src/app/components/Messages/index.jsx
- src/app/reducers/comments.test.js
- src/app/reducers/mail.js
- src/app/reducers/mail.test.js
- src/app/reducers/messages.js
- src/app/reducers/messages.test.js
- src/app/reducers/posts.test.js
- src/app/reducers/toaster.js
- src/app/router/handlers/DirectMessage.js
- src/app/router/handlers/Messages.js
Changed the handler to use a new postMessage action
which can handle both new posts and replies to
existing posts.  Most of the rest of the patch is
presentation.
> Add support for posting messages and replies

- src/app/actions/recommendedSubreddits.js
- src/app/components/RecommendedSubreddits/index.jsx
- src/app/components/RecommendedSubreddits/styles.less
- src/app/constants.js
- src/app/featureFlags.js
- src/app/pages/Comments.jsx
- src/app/reducers/index.js
- src/app/reducers/recommendedSubreddits.js
- src/app/reducers/recommendedSubreddits.test.js
- src/app/reducers/subreddits.js
- src/app/router/handlers/CommentsPage.js
Trying to get this running on staging, but in the meantime, code review! Want to get this out by EOW! I'll update when I get my staging working.
Node-api-client: https://github.com/reddit/node-api-client/pull/162
Ticket: https://reddit.atlassian.net/browse/WEB-2307
> Recommended Subreddits

- package.json
- src/app/components/CommentsPage/CommentsPageTools/index.jsx
- src/app/pages/Comments.jsx
Also honor a user's preference to ignore the suggested sort.
> Honor a post's suggestedSort for the sort dropdown

- src/app/components/Comment/CommentTools/index.jsx
- src/app/components/Comment/index.jsx
- src/app/components/CommentsList/index.jsx
- src/app/components/CommentsPage/CommentsPageTools/index.jsx
- src/app/pages/Comments.jsx
First off, there wasn't a message saying the the
post was archived.  On top of that, we allowed
the user to attempt to vote which would cause errors
in the logs.
> Handle archived posts better

- src/app/components/Post/index.jsx
👓 @dwick 
Manually tested:
- Checking a subreddit with blank ads
- Checking a subreddit with normal ads
> Serve blank ads

- src/app/router/handlers/Login.js
- src/app/router/handlers/Register.js
👓  @phil303 @schwers @drunken-economist
> Log the login_attempt and register_attempt events

- src/app/featureFlags.js
:eyeglasses: @phil303 and @schwers and @uzi
> Add a bucketing event on the client side

- src/lib/smartBannerState.js
> Fix the SmartBanner cookie expiration code

- src/app/reducers/posts.js
> Fix buggy call to  in posts reducers

- src/lib/gtm.js
👓 @schwers 
regression from https://github.com/reddit/reddit-mobile/commit/a70f8757b026879e27119ebad22b2410e7867c12
> GTM: Set frame name properly

- src/app/constants.js
- src/app/side-effect-components/CookieSync.js
👓 @dwick 
Questions:
Does the cookie key matter?
> Add visitedPosts and recentClicks to CookieSync

- src/app/router/handlers/CommentsPage.js
- src/app/router/handlers/DirectMessage.js
- src/app/router/handlers/Login.js
- src/app/router/handlers/Messages.js
- src/app/router/handlers/PostSubmit.js
- src/app/router/handlers/PostsFromSubreddit.js
- src/app/router/handlers/Register.js
- src/app/router/handlers/Status404Page.js
- src/app/router/handlers/UserProfile.js
- src/config.js
- src/lib/eventUtils.js
- src/server/initialState/dispatchInitialMeta.js
This is the event spec: https://reddit.atlassian.net/wiki/display/DA/Search+Engine+Crawl+Events
The two things I had a hard time getting were the response time, and the current server they were running on. I don't know if the concept of a server is still applicable to mweb though.
> Add crawl event tracking.

- default.vcl
> Use r2 for all endpoints with extensions.

- src/config.js
- src/server/initialState/dispatchInitialMeta.js
> Switched crawler header used.

- src/lib/errorLog.js
We currently log the entire call stack, which sometimes exceeds our log line
limits (4096 bytes). By truncating to the first 2KB, it allows us to maintain
JSON parseable log lines while still supporting source maps for the ~16 most
recent function calls of the call stack.
:eyeglasses: @schwers @uzi 
<details><summary>example error stack overflow</summary><p>
```json
Oct 31 14:55:39 mweb2x-app-9aa979aa [mweb2x] 
{
"env":"CLIENT"
"userAgent":"Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML like Gecko) Version/9.0 Mobile/13C75 Safari/601.1"
"isAPIFailure":false
"message":"Error: SecurityError: DOM Exception 18"
"requestUrl":"https://www.google.com/"
"reduxInfo":
"Redux Action Stack: \"SAVE_SCROLL_POSITION\"
\"FETCHING_RECOMMENDED_SUBREDDITS\" …
```
> Truncate error stack trace.

- package.json
- src/app/router/handlers/LiveRedirect.js
- src/app/router/index.js
Per-title, redirects live/* links to r2. Depends on the new `redirect` action pull-request: https://github.com/reddit/node-platform/pull/29
👓  @phil303 
cc: @umbrae
> Redirect live links to r2

- src/app/components/SortAndTimeSelector/index.jsx
- src/app/pages/AppMain.jsx
- src/app/router/index.js
This is due to some lost rebase changes in this
[patch](https://github.com/reddit/reddit-mobile/commit/910c563649a3d6be1e9691db9fa95b4793b9dd3c).
> Frontpage sorts broken

- src/Server.js
- src/server/session/dispatchSession.js
- src/server/session/loginproxy.js
- src/server/session/refreshproxy.js
- src/server/session/registerproxy.js
:eyeglasses: @nramadas || @schwers
> Pass debug headers to proxied endpoints

- package.json
- src/app/actions/posting.js
- src/app/components/PostSubmitModal/index.jsx
- src/app/components/ReCaptchaBox/index.jsx
- src/app/components/ReCaptchaBox/styles.less
- src/app/reducers/posting.js
- src/app/reducers/posting.test.js
👓 @uzi @KeyserSosa 
Looks like below for recaptcha:
Post request including the recaptcha response (header name will be 'g-recaptcha-response' after this PR shipped: https://github.com/reddit/node-api-client/pull/165):
Thanks.
> Replace captcha with recaptcha for mweb 2x

- src/app/components/Comment/CommentReplyForm/styles.less
- src/app/components/Comment/index.jsx
- src/app/components/Comment/styles.less
this sends the user to the permalink page for the parent comment
so that nesting does not go too deep
see uzis original pr https://github.com/reddit/reddit-mobile/pull/721 for additional insight.
👓 @uzi @schwers
> Added a link to continue Thread

- package.json
- src/lib/apiOptionsFromState.js
This updates our way of triggering debuging for employee accounts, depends on https://github.com/reddit/node-api-client/pull/177
👓  @curioussavage
> Update apiOptions for employee testing

- src/app/featureFlags.js
Use new experiment names and remove some of the targeting restrictions.
> Broaden the frontpage xpromo experiment

- src/app/actions/modal.js
- src/app/components/InterstitialListing/common.jsx
- src/app/components/ModalSwitch/index.jsx
Also tossed in a few more comments and a cleanup.
👓  @prashtx @schwers
> Add modal event for xpromo experiment

- src/app/actions/sessionRefreshing.js
> Don't recurisvely retry to refresh access tokens forever

- src/app/components/InterstitialListing/common.jsx
> NSFW subreddits don't show any images.

- src/app/actions/posts.js
- src/app/components/Post/PostContent/index.jsx
- src/app/components/Post/PostHeader/index.jsx
- src/app/components/Post/index.jsx
- src/app/constants.js
- src/app/featureFlags.js
- src/lib/eventUtils.js
https://reddit.atlassian.net/browse/WEB-2356
> add experiment to open expando on title click

- src/app/components/Post/PostContent/index.jsx
> Fix gifs not being recognized as playable

- package.json
- src/app/components/Post/PostFooter/index.jsx
- src/app/components/RelevantContent/index.jsx
👓 @schwers 
Change all instances of `disable_comments` to `disableComments`
> Change disable_comments to disableComments

- src/app/components/InterstitialListing/common.jsx
> Don't show NSFW subreddit names.

- src/app/pages/AppMain.jsx
> Add user submitted back to routes.

- src/app/components/DualPartInterstitial/Header/index.jsx
- src/app/components/IPhoneAppPreview/index.jsx
- src/config.js
> layout fixups.

- blueprints.config.js
> Add STATIC_BASE to the blueprints.

- readme.md
👓 
@schwers 
this is the commit that updated the readme from my dev inspector pull request - with the inspector part removed
> 2017 readme

- package.json
- src/Client.js
- src/app/actions/smartBanner.js
- src/app/actions/smartBannerClientOnly.js
- src/app/components/DualPartInterstitial/common.jsx
- src/app/components/InterstitialPromo/index.jsx
- src/app/reducers/smartBanner.js
- src/app/reducers/smartBanner.test.js
- src/config.js
- src/lib/branch.js
- src/lib/branchClientOnly.js
- src/lib/smartBannerState.js
The code this was based on only generated the main "clickUrl" with the branch sdk, and then statically generated the others. I kept that behavior because I wasn't sure if this was intentional. 
👓 : @prashtx @uzi
> Use the branch sdk to generate deep links.

- assets/svg/distinguish.svg
> Fix distinguish icon svg

- package.json
> Bump node-build for fonts

- src/app/components/Comment/index.jsx
- src/app/components/Post/index.jsx
👓 @birakattack @madbook 
This was causing an issue for subreddits like `CarRamrod` (mark hambly's personal sr), because it was checking against `carramrod` in the `moderatingSubreddits` list.
> Modtool fix: lowercase subreddit name isSubredditModerator

- src/app/components/Dropdown/styles.less
👓 @birakattack @madbook @powerlanguage
> Center mod & regular modal vertically

- src/app/components/ModeratorModal/index.jsx
- src/app/reducers/posts.js
Removed the errors I introduced from my mod tools patch. This removes all errors from those commits. 
:eyeglasses: @scarow
> Pep8 Cleanup

- src/app/components/Dropdown/styles.less
> Fix modal position

- src/lib/experiments.js
This is a fix for an error we are seeing in the logs:
```
Feb  6 13:41:08 mweb2x-app-92ebc6a3 [mweb2x] {
"column": "19", 
"env": "SERVER", 
"isAPIFailure": false, 
"line": "10", 
"message": "Error: Cannot read property 'features' of undefined", 
"requestUrl": "/", 
"stack": "TypeError: Cannot read property 'features' of undefined\n    
at o (/opt/reddit-mobile/bin/webpack:/src/lib/experiments.js:10:19)\n    
at Object.<anonymous> (/opt/reddit-mobile/bin/webpack:/src/app/featureFlags.js:347:26)\n    
at e.a.value (/opt/reddit-mobile/bin/webpack:/.-deps/@r/flags/flags.js:1:1876)\n    
at /opt/reddit-mobile/bin/webpack:/.-deps/@r/flags/flags.js:1:2060\n    
at Array.some (native)\n    
at /opt/reddit-mobile/bin/webpack:/.-deps/@r/flags/flags.js:1:2034\n    
at Array.some (native)\n    
at …
```
> getExperimentData is safe to call for logged out users.

- src/app/components/Comment/CommentDropdown/index.jsx
- src/app/components/Dropdown/index.jsx
- src/app/components/Dropdown/styles.less
- src/app/components/ModalBanner/index.jsx
- src/app/components/ModalBanner/styles.less
- src/app/components/ModeratorModal/index.jsx
- src/app/components/Post/PostDropdown/index.jsx
- src/app/components/Post/PostHeader/index.jsx
- src/app/less/variables.less
https://reddit.atlassian.net/browse/CE-476
This PR adds an `X` icon to comment & post modals (both regular modals and moderator modals).
https://x-modal.mobile.staging.snooguts.net
> Add x to post & comment modals

- src/Client.js
- src/lib/eventUtils.js
- src/lib/gtm.js
👓 @schwers 
related ticket: https://reddit.atlassian.net/browse/ADS-1245
> Add `userId` data layer variable

- assets/svg/flag.svg
- src/app/actions/reporting.js
- src/app/components/Comment/CommentDropdown/index.jsx
- src/app/components/Comment/CommentHeader/index.jsx
- src/app/components/Comment/CommentHeader/styles.less
- src/app/components/Comment/CommentTools/index.jsx
- src/app/components/Comment/index.jsx
- src/app/components/CommentTree/index.jsx
- src/app/components/Dropdown/index.jsx
- src/app/components/Dropdown/styles.less
- src/app/components/ModeratorModal/index.jsx
- src/app/components/Post/PostDropdown/index.jsx
- src/app/components/Post/PostFooter/index.jsx
- src/app/components/Post/PostHeader/index.jsx
- src/app/components/Post/PostHeader/styles.less
- src/app/components/Post/index.jsx
- src/app/components/ReportsModal/index.jsx
- src/app/components/ReportsModal/styles.less
- src/app/reducers/comments/data/index.js
- src/app/reducers/index.js
- src/app/reducers/reports.js
- src/lib/modToolHelpers.js
https://reddit.atlassian.net/browse/CE-369
https://reddit.atlassian.net/browse/CE-382
https://reddit.atlassian.net/browse/CE-534 (add reports modal -- just combined the PRs)
https://reddit.atlassian.net/browse/CE-373
https://reddit.atlassian.net/browse/CE-383
https://comment-report-actions.mobile.staging.snooguts.net
Note that when a post/comment gets approved, the reports are cleared on refresh.
Also note that approved posts can not be reported (you can technically report them from the interface, but a report flag will not show up).
> Comment report actions

- package.json
- src/apiClient/apiBase/APIRequestUtils.js
- src/apiClient/apiBase/Model.js
- src/apiClient/models/Account.js
- src/app/actions/xpromo.js
- src/app/components/DualPartInterstitial/Footer/index.jsx
- src/app/components/DualPartInterstitial/index.jsx
- src/app/components/DualPartInterstitial/styles.less
- src/app/components/Login/index.jsx
- src/app/components/ModalBanner/index.jsx
- src/app/components/ModeratorModal/index.jsx
- src/app/components/NavFrame/index.jsx
- src/app/components/Post/PostHeader/index.jsx
- src/app/components/RecommendedSubreddits/index.jsx
- src/app/components/XPromoWrapper/index.jsx
- src/app/constants.js
- src/app/featureFlags.js
- src/app/less/mixins/mixins.less
- src/app/reducers/smartBanner.js
- src/app/reducers/smartBanner.test.js
- src/app/router/handlers/CommentsPage.js
- src/app/selectors/xpromo.js
- src/lib/eventUtils.js
Other notable improvements:
* xpromo_ineligible event should be more accurate on listing
and index pages now.
* xpromo_dimiss and app_store_visit events should now accurately
contain experiment info and screen_view data
👓  @tomsoir @prashtx
> Add XPromo comments page interstitial.

- src/Server.js
> Remove duplicate cache control headers

- src/app/actions/comment.js
> Fix comment deletion bug

- src/app/components/OverlayMenu/styles.less
👓 @schwers 
Another small change to fix this iOS UI bug.
> Fix momentum scrolling for subscription menu in iOS

- src/apiClient/apis/PostsEndpoint.js
👓  @schwers 
This addresses: https://sentry.reddit.ue1.snooguts.net/sentry/mobile-web/issues/8492/
Not sure what exactly is null but lodash `has` will return false if the object itself is null so this should protect against whatever it is.
> Protect against apiResponse or its properties being null

- src/Client.js
> Sentry: save a ref to sentry onerror and call it in ours

- src/app/actions/ads.js
- src/lib/adblock.js
- src/lib/eventUtils.js
ticket: https://reddit.atlassian.net/browse/ADS-1384
👓 @schwers
> Send adblock status w/ad request

- src/app/actions/xpromo.js
- src/app/components/CommunityOverlayMenu/index.jsx
- src/app/components/DualPartInterstitial/index.jsx
- src/app/components/Login/index.jsx
- src/app/reducers/reports.js
- src/app/reduxMiddleware/trackXPromoEvents.js
- src/lib/eventTracker.js
- src/lib/eventUtils.js
Task: https://reddit.atlassian.net/browse/CHAN-435
> Added Promise support for the app-store-visit trace events and navigation

- src/app/components/DualPartInterstitial/Footer/index.jsx
- src/app/components/DualPartInterstitial/Footer/styles.less
- src/app/components/DualPartInterstitial/Header/index.jsx
- src/app/components/DualPartInterstitial/Header/styles.less
- src/app/components/DualPartInterstitial/index.jsx
- src/app/components/DualPartInterstitial/styles.less
- src/app/less/themes/themeify.less
- src/app/reducers/smartBanner.js
- src/app/reducers/smartBanner.test.js
Task: https://reddit.atlassian.net/browse/CHAN-476.
- also xpromo text color has been fixed in night mode.
> CHAN-476 remove xpromo dismissal while app navigation

- src/app/components/VotingBox/index.jsx
> Don't intercept comment votes

- src/app/components/Post/PostHeader/index.jsx
- src/app/components/SortAndTimeSelector/index.jsx
Display u/username for profile posts and r/subredditname for subreddit
posts.
Let the sort selector use the correct base URL for a user's posts
listing.
> Use the prefixed subreddit display name

- package.json
- src/apiClient/apiBase/apiRequest.js
- src/app/actions/loid.js
- src/app/reducers/accountRequests.js
- src/app/reducers/accountRequests.test.js
- src/app/reducers/loid.js
- src/app/reducers/loid.test.js
- src/lib/apiOptionsFromState.js
- src/server/initialState/dispatchInitialUser.js
👓  @pacejackson @phil303 @prashtx
> Support new loid cookie format.

- src/app/components/UserProfileHeader/index.jsx
> Fix an issue with a subreddit name not being lowercased

- src/app/components/CommunityHeader/index.jsx
- src/app/components/CommunityHeader/styles.less
- src/app/components/CommunityOverlayMenu/index.jsx
- src/app/components/CommunityRow/index.js
- src/app/components/UserProfileHeader/index.jsx
- src/app/components/UserProfileHeader/styles.less
- src/app/pages/UserActivity/index.jsx
- src/app/pages/UserProfile/index.jsx
* Restyle follow/subscribe buttons
* Display more things by their displayNamePrefixed format
* Display names with canonical casing
* Other little cleanups
👓  @prashtx @nramadas @schwers
> Various style fixes for profile updates

- src/app/components/CommunityOverlayMenu/index.jsx
> Update nav names

- src/server/session/dispatchSession.js
There've been a few more reports of 'Not Found' pages. After verifying on an affected device that loid and loidcreated issues weren't an issue, removing the token cookie resolved the issue. On further inspection its possible for an invalid `refreshToken`, or refresh api call failure to break requests.
👓  @birakattack @curioussavage
> Gracefully handle failures when converting or refreshing sessions

- src/app/featureFlags.js
👓  @tomsoir @prashtx 
I think this would be good to add tests for, but I wanted to get the patch in review for now.
> Fix NSFW page check in app/featureFlags

- src/app/components/Wiki/index.js
👓  @schwers | @uzi 
just a quick fix for https://www.reddit.com/r/mobileweb/comments/61ffjj/issue_with_samepage_anchor_tags_in_wiki_hitting/
> handle hash fragments in wiki links

- src/app/components/Post/PostContent/styles.less
Fixes alignment issues discovered via webcompat, ticket here: [MWEB-772](https://reddit.atlassian.net/browse/MOBILEWEB-772)
> Vertically center playback icons cross browsers

- src/app/selectors/xpromo.js
> Exclude gold users from the modal listing click experiment

- src/lib/xpromoState.js
https://reddit.atlassian.net/browse/CHAN-586
> chan-586 fix LocalStorage in private browser mode

- src/app/featureFlags.js
- src/app/selectors/xpromo.js
Task: https://reddit.atlassian.net/browse/CHAN-419
> Chan 419 loid dismiss event

- package.json
- src/Client.js
- src/app/actions/xpromoClientOnly.js
- src/config.js
- src/lib/branchClientOnly.js
@schwers - "`BRANCH_KEY` is still configured in our env variables".
> chan-338 prevent xpromo for native-app users

- src/app/constants.js
- src/app/featureFlags.js
- src/app/reducers/optOuts.js
- src/app/reducers/optOuts.test.js
https://reddit.atlassian.net/browse/CHAN-489
> chan 489 opt out link

- src/app/components/DualPartInterstitial/Footer/index.jsx
- src/lib/getSubredditFromState.js
https://reddit.atlassian.net/browse/CHAN-525
> chan-525 fix prefixed subreddit names at the XPromo banner

- src/lib/xpromoState.js
Very small patch for this one :)
https://sentry.reddit.ue1.snooguts.net/sentry/mobile-web/issues/47694/
> chan-641 fix localstorage error

- src/app/components/NavFrame/index.jsx
- src/app/selectors/xpromo.js
> Fix xpromo content padding at the bottom of Main page

- src/app/components/Post/PostHeader/index.jsx
- src/app/components/UserProfileHeader/index.jsx
- src/app/components/UserProfileHeader/styles.less
- src/app/pages/UserActivity/index.jsx
- src/app/pages/UserProfile/index.jsx
> task VOICE-258 -- removing of verified icon for the user profile

- src/apiClient/models/Subreddit.js
- src/app/components/NSFWWrapper/index.jsx
- src/app/pages/UserActivity/index.jsx
- src/app/pages/UserProfile/index.jsx
- src/server/initialState/dispatchInitialOver18.js
For profiles that have been marked as NSFW, we should use the same NSFW
interstitial flow that we do for subreddits.
> Use an interstitial for over18 profiles

- src/app/pages/PostsFromSubreddit.jsx
Fixes linting errors as well as one warning caused by my previous commit
> Fix linting errors in PostsFromSubreddit.jsx

- src/app/components/LoadingXpromo/OptOutWrapper/index.jsx
- src/app/components/LoadingXpromo/OptOutWrapper/index.test.js
- src/app/components/LoadingXpromo/OptOutWrapper/script.js
- src/app/components/SettingsOverlayMenu/index.jsx
- src/app/constants.js
- src/app/featureFlags.js
- src/app/pages/PostsFromSubreddit.jsx
- src/app/reducers/optOuts.js
- src/app/selectors/xpromo.js
https://reddit.atlassian.net/browse/CHAN-673
There are two optOut links now (regular and for the menu):
http://localhost:4444/?no_xpromo_interstitial=true
http://localhost:4444/?no_xpromo_interstitial_menu=true
> Add menu OptOut XPromo link

- src/app/pages/UserActivity/index.jsx
- src/app/pages/UserProfile/index.jsx
The problem is that we're checking for a value in
the userSubreddit object when it's not already loaded.
Instead, we add a guard to that.
👓  @prashtx
> Fix an error when loading a user's own profile page

- src/app/components/XPromoListingClickModal/index.jsx
- src/app/constants.js
- src/app/featureFlags.js
- src/app/selectors/xpromo.js
https://reddit.atlassian.net/browse/CHAN-719
> Enable modal listing click XPromo

- src/lib/eventUtils.js
- src/lib/getSessionIdFromCookie.js
- test/lib/getSessionIdFromCookie.test.js
https://reddit.atlassian.net/browse/CHAN-728
Reproduced when the cookie 'session_tracker' does not exist.
> Fix client<>session deeplink generation bug

- src/app/actions/sessionTracker.js
- src/app/reducers/index.js
- src/app/reducers/sessionTracker.js
- src/app/reducers/sessionTracker.test.js
- src/lib/apiOptionsFromState.js
- src/lib/eventUtils.js
- src/lib/getSessionIdFromCookie.js
- src/lib/getSessionIdFromCookie.test.js
- src/server/initialState/dispatchInitialUser.js
https://reddit.atlassian.net/browse/GROW-727
P.S. XPromo on loading has been tested also.
> Add SessionTracker to state and fix cookie issue

- src/app/components/BannerAd/index.jsx
> Respect gold for banners

- src/app/actions/posts.js
- src/app/components/HTML5StreamPlayer/index.jsx
- src/app/components/HTML5StreamPlayer/styles.less
- src/app/constants.js
- src/lib/eventUtils.js
- src/platform/pageUtils.js
This implements async event tracking for several consumption events of the new self-hosted video content.
> *Implement events data for self hosted video content on mobile web

- src/app/pages/Comments.jsx
> Remove adception

- package.json
@r/widgets introduced a breaking change in a minor revision.
👓  @griffinmichl
> Fix broken build.

- src/Client.js
> Ignore dfp errors

- src/app/components/BannerAd/index.jsx
- src/lib/createBannerProperties.js
> Prevent banner ads from updating unnecessarily

- src/lib/dfp.js
- src/lib/gtm.js
👓 @griffinmichl 
ticket: https://reddit.atlassian.net/browse/ADS-1934
> Remove DNT support

- src/app/selectors/xpromo.js
The ‘download the reddit app for a better experience’ was showing up in reddit video comments pages on third party apps.
This came across quite aggressive towards third party apps.
To ensure good relations with third party app developers we are removing it (from comments location only).
https://reddit.atlassian.net/browse/MEDIA-383
> Prevent reddit video comments page 'download app' interstitial
